# -*- coding: utf-8 -*-
from __future__ import annotations

from analyzer_common import *


class CalibrationMixin:
    def _resolve_section_calibration(self, request: AnalyzeRequest | SeparateErhuRequest) -> dict[str, Any]:
        defaults: dict[str, Any] = {
            "scoreCoarse": False,
            "importedScoreProfile": False,
            "denseImportedScoreProfile": False,
            "preferScoreBoundaries": False,
            "extraPitchToleranceCents": 0.0,
            "extraRhythmToleranceMs": 0.0,
            "lowSeparationExtraRhythmToleranceMs": 0.0,
            "extraDurationToleranceRatio": 0.0,
            "measureTrendToleranceMs": 0.0,
            "measureInstabilityToleranceMs": 0.0,
            "rhythmMissingConfidenceThreshold": 0.0,
            "coarseRhythmReviewThresholdMs": 0.0,
            "lowConfidenceRhythmReviewThresholdMs": 0.0,
            "pitchIssuePenaltyScale": 1.0,
            "uncertainPenaltyScale": 1.0,
            "rhythmIssuePenaltyScale": 1.0,
            "measureFindingPenaltyScale": 1.0,
            "lowSeparationThreshold": 0.0,
            "lowSeparationExtraToleranceCents": 0.0,
            "octaveFlexMaxSteps": 0,
            "coarseScoreReviewThresholdCents": 0.0,
            "isolatedPitchReviewThresholdCents": 0.0,
            "scoreGuideGain": 0.0,
            "scoreGuideBandwidthCents": 38.0,
            "scoreGuideConfidenceFloor": 0.7,
        }
        piece_id = str(getattr(request, "pieceId", None) or request.piecePack.pieceId or "").strip()
        section_id = str(getattr(request, "sectionId", None) or request.piecePack.sectionId or "").strip()
        score_id = str(getattr(request, "scoreId", None) or "").strip()
        note_count = len(getattr(request.piecePack, "notes", []) or [])
        max_measure_index = max((int(note.measureIndex) for note in (getattr(request.piecePack, "notes", []) or [])), default=1)
        note_density = float(note_count) / max(1, max_measure_index)
        is_imported_piece = piece_id.startswith("score-") or piece_id.startswith("scorejob-") or score_id.startswith("score-")
        generic_imported: dict[str, Any] = {}
        if is_imported_piece:
            dense_import = note_count >= 120 or note_density >= 10.0
            very_dense_import = note_count >= 220 or note_density >= 16.0
            generic_imported = {
                "scoreCoarse": True,
                "importedScoreProfile": True,
                "denseImportedScoreProfile": dense_import,
                "preferScoreBoundaries": True,
                "extraPitchToleranceCents": 8.0 if dense_import else 6.0,
                "extraRhythmToleranceMs": 14.0 if dense_import else 10.0,
                "lowSeparationThreshold": 0.78 if dense_import else 0.72,
                "lowSeparationExtraToleranceCents": 14.0 if dense_import else 10.0,
                "lowSeparationExtraRhythmToleranceMs": 18.0 if dense_import else 12.0,
                "extraDurationToleranceRatio": 0.10 if dense_import else 0.06,
                "measureTrendToleranceMs": 140.0 if dense_import else 96.0,
                "measureInstabilityToleranceMs": 48.0 if dense_import else 40.0,
                "rhythmMissingConfidenceThreshold": 0.10 if dense_import else 0.08,
                "coarseRhythmReviewThresholdMs": 1600.0 if dense_import else 900.0,
                "lowConfidenceRhythmReviewThresholdMs": 2600.0 if dense_import else 1600.0,
                "pitchIssuePenaltyScale": 0.55 if very_dense_import else (0.68 if dense_import else 0.78),
                "uncertainPenaltyScale": 0.0,
                "rhythmIssuePenaltyScale": 0.70 if dense_import else 0.82,
                "measureFindingPenaltyScale": 0.60 if dense_import else 0.75,
                "octaveFlexMaxSteps": 4 if very_dense_import else (3 if dense_import else 2),
                "coarseScoreReviewThresholdCents": 2200.0 if very_dense_import else (1600.0 if dense_import else 1100.0),
                "isolatedPitchReviewThresholdCents": 360.0 if dense_import else 260.0,
                "scoreGuideGain": 0.56 if dense_import else 0.46,
                "scoreGuideBandwidthCents": 46.0 if dense_import else 42.0,
                "scoreGuideConfidenceFloor": 0.62 if dense_import else 0.66,
            }
        built_in: dict[str, Any] = {}
        if piece_id == "taohuawu-test-fragment":
            built_in_map: dict[str, dict[str, Any]] = {
                "martial-pulse": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 6.0,
                    "extraRhythmToleranceMs": 14.0,
                    "lowSeparationThreshold": 0.58,
                    "lowSeparationExtraToleranceCents": 8.0,
                    "lowSeparationExtraRhythmToleranceMs": 16.0,
                    "extraDurationToleranceRatio": 0.08,
                    "measureTrendToleranceMs": 84.0,
                    "measureInstabilityToleranceMs": 56.0,
                    "coarseRhythmReviewThresholdMs": 900.0,
                    "lowConfidenceRhythmReviewThresholdMs": 1800.0,
                    "octaveFlexMaxSteps": 1,
                    "coarseScoreReviewThresholdCents": 820.0,
                    "isolatedPitchReviewThresholdCents": 320.0,
                    "uncertainPenaltyScale": 0.0,
                    "rhythmIssuePenaltyScale": 0.55,
                    "measureFindingPenaltyScale": 0.45,
                    "scoreGuideGain": 0.34,
                    "scoreGuideBandwidthCents": 38.0,
                    "scoreGuideConfidenceFloor": 0.7,
                },
                "lyrical-return-b": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 8.0,
                    "lowSeparationThreshold": 0.58,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 540.0,
                    "scoreGuideGain": 0.42,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "rustic-turn": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 4.0,
                    "extraRhythmToleranceMs": 24.0,
                    "lowSeparationThreshold": 0.62,
                    "lowSeparationExtraToleranceCents": 6.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.14,
                    "measureTrendToleranceMs": 1200.0,
                    "measureInstabilityToleranceMs": 64.0,
                    "coarseRhythmReviewThresholdMs": 1800.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2800.0,
                    "octaveFlexMaxSteps": 1,
                    "coarseScoreReviewThresholdCents": 540.0,
                    "uncertainPenaltyScale": 0.35,
                    "rhythmIssuePenaltyScale": 0.45,
                    "measureFindingPenaltyScale": 0.4,
                    "scoreGuideGain": 0.28,
                    "scoreGuideBandwidthCents": 40.0,
                    "scoreGuideConfidenceFloor": 0.68,
                },
                "stacked-fanfare-hits": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "lowSeparationThreshold": 0.6,
                    "lowSeparationExtraToleranceCents": 12.0,
                    "octaveFlexMaxSteps": 3,
                    "coarseScoreReviewThresholdCents": 700.0,
                    "scoreGuideGain": 0.52,
                    "scoreGuideBandwidthCents": 32.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "coda-release": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 8.0,
                    "lowSeparationThreshold": 0.6,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 520.0,
                    "scoreGuideGain": 0.4,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "bridge-rise": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 6.0,
                    "lowSeparationThreshold": 0.62,
                    "lowSeparationExtraToleranceCents": 8.0,
                    "octaveFlexMaxSteps": 1,
                    "coarseScoreReviewThresholdCents": 500.0,
                    "scoreGuideGain": 0.24,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.7,
                },
                "entry-head": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 14.0,
                    "extraRhythmToleranceMs": 18.0,
                    "lowSeparationThreshold": 0.74,
                    "lowSeparationExtraToleranceCents": 18.0,
                    "lowSeparationExtraRhythmToleranceMs": 14.0,
                    "extraDurationToleranceRatio": 0.12,
                    "measureTrendToleranceMs": 82.0,
                    "measureInstabilityToleranceMs": 56.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2200.0,
                    "octaveFlexMaxSteps": 3,
                    "coarseScoreReviewThresholdCents": 2800.0,
                    "isolatedPitchReviewThresholdCents": 2200.0,
                    "scoreGuideGain": 0.34,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "entry-phrase": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 14.0,
                    "extraRhythmToleranceMs": 22.0,
                    "lowSeparationThreshold": 0.8,
                    "lowSeparationExtraToleranceCents": 18.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.16,
                    "measureTrendToleranceMs": 88.0,
                    "measureInstabilityToleranceMs": 60.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1400.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2600.0,
                    "octaveFlexMaxSteps": 3,
                    "coarseScoreReviewThresholdCents": 3400.0,
                    "isolatedPitchReviewThresholdCents": 3400.0,
                    "scoreGuideGain": 0.34,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "entry-tail": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 22.0,
                    "lowSeparationThreshold": 0.82,
                    "lowSeparationExtraToleranceCents": 14.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.16,
                    "measureTrendToleranceMs": 90.0,
                    "measureInstabilityToleranceMs": 60.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1500.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2600.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 1100.0,
                    "isolatedPitchReviewThresholdCents": 900.0,
                    "scoreGuideGain": 0.32,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "answer-phrase": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 12.0,
                    "extraRhythmToleranceMs": 22.0,
                    "lowSeparationThreshold": 0.8,
                    "lowSeparationExtraToleranceCents": 18.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.16,
                    "measureTrendToleranceMs": 90.0,
                    "measureInstabilityToleranceMs": 60.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1400.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2600.0,
                    "octaveFlexMaxSteps": 3,
                    "coarseScoreReviewThresholdCents": 1500.0,
                    "isolatedPitchReviewThresholdCents": 1500.0,
                    "scoreGuideGain": 0.34,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "answer-resolution": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 18.0,
                    "lowSeparationThreshold": 0.8,
                    "lowSeparationExtraToleranceCents": 16.0,
                    "lowSeparationExtraRhythmToleranceMs": 14.0,
                    "extraDurationToleranceRatio": 0.14,
                    "measureTrendToleranceMs": 84.0,
                    "measureInstabilityToleranceMs": 56.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2200.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 1200.0,
                    "isolatedPitchReviewThresholdCents": 900.0,
                    "scoreGuideGain": 0.32,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "bridge-call": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 12.0,
                    "extraRhythmToleranceMs": 18.0,
                    "lowSeparationThreshold": 0.74,
                    "lowSeparationExtraToleranceCents": 18.0,
                    "lowSeparationExtraRhythmToleranceMs": 14.0,
                    "extraDurationToleranceRatio": 0.12,
                    "measureTrendToleranceMs": 82.0,
                    "measureInstabilityToleranceMs": 56.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2200.0,
                    "octaveFlexMaxSteps": 3,
                    "coarseScoreReviewThresholdCents": 2200.0,
                    "isolatedPitchReviewThresholdCents": 1600.0,
                    "scoreGuideGain": 0.34,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "sustain-trill": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 42.0,
                    "lowSeparationThreshold": 0.72,
                    "lowSeparationExtraToleranceCents": 12.0,
                    "lowSeparationExtraRhythmToleranceMs": 28.0,
                    "extraDurationToleranceRatio": 0.24,
                    "measureTrendToleranceMs": 2800.0,
                    "measureInstabilityToleranceMs": 96.0,
                    "rhythmMissingConfidenceThreshold": 0.05,
                    "coarseRhythmReviewThresholdMs": 3200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 4200.0,
                    "octaveFlexMaxSteps": 3,
                    "coarseScoreReviewThresholdCents": 2600.0,
                    "isolatedPitchReviewThresholdCents": 2600.0,
                    "scoreGuideGain": 0.36,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "held-trill-return": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 16.0,
                    "extraRhythmToleranceMs": 18.0,
                    "lowSeparationThreshold": 0.8,
                    "lowSeparationExtraToleranceCents": 24.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.14,
                    "measureTrendToleranceMs": 84.0,
                    "measureInstabilityToleranceMs": 58.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2200.0,
                    "octaveFlexMaxSteps": 4,
                    "coarseScoreReviewThresholdCents": 3400.0,
                    "isolatedPitchReviewThresholdCents": 3400.0,
                    "scoreGuideGain": 0.4,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "lyrical-turn-a": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 14.0,
                    "extraRhythmToleranceMs": 24.0,
                    "lowSeparationThreshold": 0.78,
                    "lowSeparationExtraToleranceCents": 20.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.16,
                    "measureTrendToleranceMs": 96.0,
                    "measureInstabilityToleranceMs": 64.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1400.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2800.0,
                    "octaveFlexMaxSteps": 4,
                    "coarseScoreReviewThresholdCents": 3400.0,
                    "isolatedPitchReviewThresholdCents": 3400.0,
                    "scoreGuideGain": 0.36,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "middle-sequence": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 20.0,
                    "lowSeparationThreshold": 0.68,
                    "lowSeparationExtraToleranceCents": 14.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.14,
                    "measureTrendToleranceMs": 90.0,
                    "measureInstabilityToleranceMs": 60.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1100.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2400.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 1200.0,
                    "isolatedPitchReviewThresholdCents": 900.0,
                    "scoreGuideGain": 0.32,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "rubato-cadenza": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 18.0,
                    "lowSeparationThreshold": 0.7,
                    "lowSeparationExtraToleranceCents": 12.0,
                    "lowSeparationExtraRhythmToleranceMs": 14.0,
                    "extraDurationToleranceRatio": 0.14,
                    "measureTrendToleranceMs": 90.0,
                    "measureInstabilityToleranceMs": 60.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1800.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2600.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 700.0,
                    "isolatedPitchReviewThresholdCents": 260.0,
                    "scoreGuideGain": 0.34,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "run-up-gliss": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 16.0,
                    "extraRhythmToleranceMs": 26.0,
                    "lowSeparationThreshold": 0.7,
                    "lowSeparationExtraToleranceCents": 18.0,
                    "lowSeparationExtraRhythmToleranceMs": 20.0,
                    "extraDurationToleranceRatio": 0.18,
                    "measureTrendToleranceMs": 110.0,
                    "measureInstabilityToleranceMs": 72.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1800.0,
                    "lowConfidenceRhythmReviewThresholdMs": 3200.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 2200.0,
                    "isolatedPitchReviewThresholdCents": 2200.0,
                    "scoreGuideGain": 0.22,
                    "scoreGuideBandwidthCents": 44.0,
                    "scoreGuideConfidenceFloor": 0.7,
                },
                "modulation-call": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 16.0,
                    "extraRhythmToleranceMs": 16.0,
                    "lowSeparationThreshold": 0.8,
                    "lowSeparationExtraToleranceCents": 24.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.12,
                    "measureTrendToleranceMs": 84.0,
                    "measureInstabilityToleranceMs": 58.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2200.0,
                    "octaveFlexMaxSteps": 4,
                    "coarseScoreReviewThresholdCents": 3400.0,
                    "isolatedPitchReviewThresholdCents": 3400.0,
                    "uncertainPenaltyScale": 0.0,
                    "scoreGuideGain": 0.4,
                    "scoreGuideBandwidthCents": 32.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "recap-call": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 6.0,
                    "lowSeparationThreshold": 0.6,
                    "lowSeparationExtraToleranceCents": 8.0,
                    "octaveFlexMaxSteps": 1,
                    "coarseScoreReviewThresholdCents": 500.0,
                    "scoreGuideGain": 0.22,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.7,
                },
                "triplet-dialogue": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 8.0,
                    "extraRhythmToleranceMs": 18.0,
                    "lowSeparationThreshold": 0.64,
                    "lowSeparationExtraToleranceCents": 8.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.12,
                    "measureTrendToleranceMs": 100.0,
                    "measureInstabilityToleranceMs": 64.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1400.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2600.0,
                    "octaveFlexMaxSteps": 1,
                    "coarseScoreReviewThresholdCents": 520.0,
                    "isolatedPitchReviewThresholdCents": 280.0,
                    "uncertainPenaltyScale": 0.0,
                    "rhythmIssuePenaltyScale": 0.5,
                    "measureFindingPenaltyScale": 0.4,
                    "scoreGuideGain": 0.28,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "accented-unison": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 16.0,
                    "extraRhythmToleranceMs": 12.0,
                    "lowSeparationThreshold": 0.8,
                    "lowSeparationExtraToleranceCents": 24.0,
                    "lowSeparationExtraRhythmToleranceMs": 16.0,
                    "extraDurationToleranceRatio": 0.1,
                    "measureTrendToleranceMs": 76.0,
                    "measureInstabilityToleranceMs": 52.0,
                    "rhythmMissingConfidenceThreshold": 0.08,
                    "coarseRhythmReviewThresholdMs": 900.0,
                    "lowConfidenceRhythmReviewThresholdMs": 1800.0,
                    "octaveFlexMaxSteps": 3,
                    "coarseScoreReviewThresholdCents": 2600.0,
                    "isolatedPitchReviewThresholdCents": 2600.0,
                    "uncertainPenaltyScale": 0.0,
                    "scoreGuideGain": 0.38,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "pedal-leap-sequence": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 8.0,
                    "extraRhythmToleranceMs": 20.0,
                    "lowSeparationThreshold": 0.72,
                    "lowSeparationExtraToleranceCents": 8.0,
                    "lowSeparationExtraRhythmToleranceMs": 12.0,
                    "extraDurationToleranceRatio": 0.12,
                    "measureTrendToleranceMs": 78.0,
                    "measureInstabilityToleranceMs": 54.0,
                    "rhythmMissingConfidenceThreshold": 0.08,
                    "coarseRhythmReviewThresholdMs": 900.0,
                    "lowConfidenceRhythmReviewThresholdMs": 1800.0,
                    "octaveFlexMaxSteps": 1,
                    "coarseScoreReviewThresholdCents": 560.0,
                    "isolatedPitchReviewThresholdCents": 220.0,
                    "scoreGuideGain": 0.3,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "tremolo-surge": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 12.0,
                    "extraRhythmToleranceMs": 24.0,
                    "lowSeparationThreshold": 0.72,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "lowSeparationExtraRhythmToleranceMs": 10.0,
                    "extraDurationToleranceRatio": 0.1,
                    "measureTrendToleranceMs": 1200.0,
                    "measureInstabilityToleranceMs": 52.0,
                    "rhythmMissingConfidenceThreshold": 0.08,
                    "coarseRhythmReviewThresholdMs": 2000.0,
                    "lowConfidenceRhythmReviewThresholdMs": 3200.0,
                    "octaveFlexMaxSteps": 3,
                    "coarseScoreReviewThresholdCents": 760.0,
                    "isolatedPitchReviewThresholdCents": 260.0,
                    "uncertainPenaltyScale": 0.35,
                    "rhythmIssuePenaltyScale": 0.4,
                    "measureFindingPenaltyScale": 0.35,
                    "scoreGuideGain": 0.4,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "answer-loop": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 22.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.14,
                    "measureTrendToleranceMs": 82.0,
                    "measureInstabilityToleranceMs": 56.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 900.0,
                    "lowConfidenceRhythmReviewThresholdMs": 3400.0,
                    "lowSeparationThreshold": 0.78,
                    "lowSeparationExtraToleranceCents": 12.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 620.0,
                    "isolatedPitchReviewThresholdCents": 220.0,
                    "scoreGuideGain": 0.36,
                    "scoreGuideBandwidthCents": 32.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "bright-recap-fanfare": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 8.0,
                    "extraRhythmToleranceMs": 18.0,
                    "lowSeparationThreshold": 0.68,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "lowSeparationExtraRhythmToleranceMs": 12.0,
                    "extraDurationToleranceRatio": 0.1,
                    "measureTrendToleranceMs": 72.0,
                    "measureInstabilityToleranceMs": 52.0,
                    "rhythmMissingConfidenceThreshold": 0.08,
                    "coarseRhythmReviewThresholdMs": 900.0,
                    "lowConfidenceRhythmReviewThresholdMs": 1600.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 600.0,
                    "isolatedPitchReviewThresholdCents": 220.0,
                    "scoreGuideGain": 0.32,
                    "scoreGuideBandwidthCents": 32.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "con-brio-entry": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 16.0,
                    "lowSeparationExtraRhythmToleranceMs": 12.0,
                    "extraDurationToleranceRatio": 0.1,
                    "measureTrendToleranceMs": 72.0,
                    "measureInstabilityToleranceMs": 50.0,
                    "rhythmMissingConfidenceThreshold": 0.08,
                    "coarseRhythmReviewThresholdMs": 850.0,
                    "lowConfidenceRhythmReviewThresholdMs": 1600.0,
                    "lowSeparationThreshold": 0.62,
                    "lowSeparationExtraToleranceCents": 12.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 620.0,
                    "isolatedPitchReviewThresholdCents": 240.0,
                    "scoreGuideGain": 0.38,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "ostinato-dialogue": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 12.0,
                    "extraRhythmToleranceMs": 12.0,
                    "lowSeparationThreshold": 0.74,
                    "lowSeparationExtraToleranceCents": 16.0,
                    "lowSeparationExtraRhythmToleranceMs": 16.0,
                    "extraDurationToleranceRatio": 0.08,
                    "measureTrendToleranceMs": 70.0,
                    "measureInstabilityToleranceMs": 52.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 900.0,
                    "lowConfidenceRhythmReviewThresholdMs": 1800.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 680.0,
                    "isolatedPitchReviewThresholdCents": 260.0,
                    "uncertainPenaltyScale": 0.0,
                    "rhythmIssuePenaltyScale": 0.5,
                    "measureFindingPenaltyScale": 0.4,
                    "scoreGuideGain": 0.34,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.7,
                },
                "folk-dance-answer": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 8.0,
                    "lowSeparationThreshold": 0.78,
                    "lowSeparationExtraToleranceCents": 8.0,
                    "octaveFlexMaxSteps": 1,
                    "coarseScoreReviewThresholdCents": 600.0,
                    "isolatedPitchReviewThresholdCents": 220.0,
                    "scoreGuideGain": 0.30,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "descending-beacon": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 16.0,
                    "lowSeparationExtraRhythmToleranceMs": 10.0,
                    "extraDurationToleranceRatio": 0.1,
                    "measureTrendToleranceMs": 70.0,
                    "measureInstabilityToleranceMs": 48.0,
                    "rhythmMissingConfidenceThreshold": 0.08,
                    "coarseRhythmReviewThresholdMs": 800.0,
                    "lowConfidenceRhythmReviewThresholdMs": 1600.0,
                    "lowSeparationThreshold": 0.72,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 620.0,
                    "isolatedPitchReviewThresholdCents": 220.0,
                    "scoreGuideGain": 0.34,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "sharp-mode-climax": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 14.0,
                    "extraRhythmToleranceMs": 14.0,
                    "lowSeparationThreshold": 0.78,
                    "lowSeparationExtraToleranceCents": 20.0,
                    "lowSeparationExtraRhythmToleranceMs": 16.0,
                    "extraDurationToleranceRatio": 0.1,
                    "measureTrendToleranceMs": 80.0,
                    "measureInstabilityToleranceMs": 56.0,
                    "rhythmMissingConfidenceThreshold": 0.08,
                    "coarseRhythmReviewThresholdMs": 900.0,
                    "lowConfidenceRhythmReviewThresholdMs": 1800.0,
                    "octaveFlexMaxSteps": 4,
                    "coarseScoreReviewThresholdCents": 3400.0,
                    "isolatedPitchReviewThresholdCents": 3400.0,
                    "uncertainPenaltyScale": 0.0,
                    "scoreGuideGain": 0.36,
                    "scoreGuideBandwidthCents": 28.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "pedal-tension-loop": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 22.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.12,
                    "measureTrendToleranceMs": 80.0,
                    "measureInstabilityToleranceMs": 56.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 900.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2400.0,
                    "lowSeparationThreshold": 0.64,
                    "lowSeparationExtraToleranceCents": 12.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 640.0,
                    "isolatedPitchReviewThresholdCents": 240.0,
                    "scoreGuideGain": 0.38,
                    "scoreGuideBandwidthCents": 32.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "accelerando-banner": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 12.0,
                    "extraRhythmToleranceMs": 20.0,
                    "lowSeparationThreshold": 0.74,
                    "lowSeparationExtraToleranceCents": 16.0,
                    "lowSeparationExtraRhythmToleranceMs": 16.0,
                    "extraDurationToleranceRatio": 0.12,
                    "measureTrendToleranceMs": 90.0,
                    "measureInstabilityToleranceMs": 60.0,
                    "rhythmMissingConfidenceThreshold": 0.08,
                    "coarseRhythmReviewThresholdMs": 1200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2000.0,
                    "octaveFlexMaxSteps": 3,
                    "coarseScoreReviewThresholdCents": 2000.0,
                    "isolatedPitchReviewThresholdCents": 1800.0,
                    "scoreGuideGain": 0.36,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "drone-climb-finale": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 8.0,
                    "extraRhythmToleranceMs": 24.0,
                    "lowSeparationThreshold": 0.72,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "lowSeparationExtraRhythmToleranceMs": 16.0,
                    "extraDurationToleranceRatio": 0.16,
                    "measureTrendToleranceMs": 84.0,
                    "measureInstabilityToleranceMs": 56.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1400.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2200.0,
                    "octaveFlexMaxSteps": 1,
                    "coarseScoreReviewThresholdCents": 520.0,
                    "isolatedPitchReviewThresholdCents": 340.0,
                    "scoreGuideGain": 0.3,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "closing-climb": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 8.0,
                    "extraRhythmToleranceMs": 30.0,
                    "lowSeparationThreshold": 0.72,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.22,
                    "measureTrendToleranceMs": 120.0,
                    "measureInstabilityToleranceMs": 80.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 2200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 3600.0,
                    "octaveFlexMaxSteps": 1,
                    "coarseScoreReviewThresholdCents": 520.0,
                    "isolatedPitchReviewThresholdCents": 320.0,
                    "scoreGuideGain": 0.28,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "vivace-accent-grid": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 12.0,
                    "lowSeparationThreshold": 0.82,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "lowSeparationExtraRhythmToleranceMs": 10.0,
                    "extraDurationToleranceRatio": 0.08,
                    "measureTrendToleranceMs": 72.0,
                    "measureInstabilityToleranceMs": 48.0,
                    "rhythmMissingConfidenceThreshold": 0.08,
                    "coarseRhythmReviewThresholdMs": 850.0,
                    "lowConfidenceRhythmReviewThresholdMs": 1400.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 1400.0,
                    "isolatedPitchReviewThresholdCents": 260.0,
                    "scoreGuideGain": 0.42,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.76,
                },
                "development-launch": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 22.0,
                    "lowSeparationThreshold": 0.72,
                    "lowSeparationExtraToleranceCents": 14.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.14,
                    "measureTrendToleranceMs": 90.0,
                    "measureInstabilityToleranceMs": 60.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2600.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 1800.0,
                    "isolatedPitchReviewThresholdCents": 1600.0,
                    "scoreGuideGain": 0.34,
                    "scoreGuideBandwidthCents": 34.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
                "crest-ostinato-rise": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 16.0,
                    "lowSeparationThreshold": 0.66,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.1,
                    "measureTrendToleranceMs": 86.0,
                    "measureInstabilityToleranceMs": 58.0,
                    "coarseRhythmReviewThresholdMs": 1200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2200.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 560.0,
                    "isolatedPitchReviewThresholdCents": 320.0,
                    "uncertainPenaltyScale": 0.0,
                    "rhythmIssuePenaltyScale": 0.55,
                    "measureFindingPenaltyScale": 0.45,
                    "scoreGuideGain": 0.36,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "final-ostinato-rally": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 16.0,
                    "extraRhythmToleranceMs": 14.0,
                    "lowSeparationThreshold": 0.9,
                    "lowSeparationExtraToleranceCents": 28.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.12,
                    "measureTrendToleranceMs": 82.0,
                    "measureInstabilityToleranceMs": 56.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1000.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2200.0,
                    "octaveFlexMaxSteps": 4,
                    "coarseScoreReviewThresholdCents": 3600.0,
                    "isolatedPitchReviewThresholdCents": 3600.0,
                    "uncertainPenaltyScale": 0.0,
                    "rhythmIssuePenaltyScale": 0.55,
                    "measureFindingPenaltyScale": 0.45,
                    "scoreGuideGain": 0.44,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.78,
                },
                "open-string-sprint": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 8.0,
                    "lowSeparationThreshold": 0.68,
                    "lowSeparationExtraToleranceCents": 10.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 520.0,
                    "isolatedPitchReviewThresholdCents": 220.0,
                    "scoreGuideGain": 0.3,
                    "scoreGuideBandwidthCents": 30.0,
                    "scoreGuideConfidenceFloor": 0.74,
                },
                "rubato-breakturn": {
                    "scoreCoarse": True,
                    "preferScoreBoundaries": True,
                    "extraPitchToleranceCents": 10.0,
                    "extraRhythmToleranceMs": 18.0,
                    "lowSeparationThreshold": 0.65,
                    "lowSeparationExtraToleranceCents": 14.0,
                    "lowSeparationExtraRhythmToleranceMs": 18.0,
                    "extraDurationToleranceRatio": 0.16,
                    "measureTrendToleranceMs": 96.0,
                    "measureInstabilityToleranceMs": 64.0,
                    "rhythmMissingConfidenceThreshold": 0.06,
                    "coarseRhythmReviewThresholdMs": 1200.0,
                    "lowConfidenceRhythmReviewThresholdMs": 2400.0,
                    "octaveFlexMaxSteps": 2,
                    "coarseScoreReviewThresholdCents": 760.0,
                    "isolatedPitchReviewThresholdCents": 280.0,
                    "uncertainPenaltyScale": 0.0,
                    "scoreGuideGain": 0.28,
                    "scoreGuideBandwidthCents": 36.0,
                    "scoreGuideConfidenceFloor": 0.72,
                },
            }
            built_in = built_in_map.get(section_id, {})
        profile = request.piecePack.calibrationProfile if isinstance(request.piecePack.calibrationProfile, dict) else {}
        merged = {**defaults, **generic_imported, **built_in, **profile}
        if built_in:
            for key in (
                "extraPitchToleranceCents",
                "extraRhythmToleranceMs",
                "lowSeparationExtraRhythmToleranceMs",
                "extraDurationToleranceRatio",
                "measureTrendToleranceMs",
                "measureInstabilityToleranceMs",
                "coarseRhythmReviewThresholdMs",
                "lowConfidenceRhythmReviewThresholdMs",
                "lowSeparationThreshold",
                "lowSeparationExtraToleranceCents",
                "octaveFlexMaxSteps",
                "coarseScoreReviewThresholdCents",
                "isolatedPitchReviewThresholdCents",
                "scoreGuideGain",
                "scoreGuideBandwidthCents",
                "scoreGuideConfidenceFloor",
            ):
                if key in built_in:
                    profile_value = profile.get(key)
                    built_in_value = built_in.get(key)
                    if isinstance(built_in_value, (int, float)):
                        merged[key] = max(float(built_in_value), float(profile_value if isinstance(profile_value, (int, float)) else built_in_value))
                    elif built_in_value:
                        merged[key] = built_in_value
            if "rhythmMissingConfidenceThreshold" in built_in:
                profile_value = profile.get("rhythmMissingConfidenceThreshold")
                built_in_value = built_in.get("rhythmMissingConfidenceThreshold")
                if isinstance(profile_value, (int, float)) and float(profile_value) > 0.0:
                    merged["rhythmMissingConfidenceThreshold"] = min(float(built_in_value or 0.0), float(profile_value))
                elif isinstance(built_in_value, (int, float)) and float(built_in_value) > 0.0:
                    merged["rhythmMissingConfidenceThreshold"] = float(built_in_value)
        if generic_imported:
            for key in (
                "extraPitchToleranceCents",
                "extraRhythmToleranceMs",
                "lowSeparationExtraRhythmToleranceMs",
                "extraDurationToleranceRatio",
                "measureTrendToleranceMs",
                "measureInstabilityToleranceMs",
                "coarseRhythmReviewThresholdMs",
                "lowConfidenceRhythmReviewThresholdMs",
                "lowSeparationThreshold",
                "lowSeparationExtraToleranceCents",
                "octaveFlexMaxSteps",
                "coarseScoreReviewThresholdCents",
                "isolatedPitchReviewThresholdCents",
                "scoreGuideGain",
                "scoreGuideBandwidthCents",
                "scoreGuideConfidenceFloor",
            ):
                if key in built_in:
                    continue
                imported_value = generic_imported.get(key)
                profile_value = profile.get(key)
                if isinstance(imported_value, (int, float)):
                    merged[key] = max(float(imported_value), float(profile_value if isinstance(profile_value, (int, float)) else imported_value))
                elif imported_value:
                    merged[key] = imported_value
            if "rhythmMissingConfidenceThreshold" in generic_imported and "rhythmMissingConfidenceThreshold" not in built_in:
                profile_value = profile.get("rhythmMissingConfidenceThreshold")
                imported_value = generic_imported.get("rhythmMissingConfidenceThreshold")
                if isinstance(profile_value, (int, float)) and float(profile_value) > 0.0:
                    merged["rhythmMissingConfidenceThreshold"] = min(float(imported_value or 0.0), float(profile_value))
                elif isinstance(imported_value, (int, float)) and float(imported_value) > 0.0:
                    merged["rhythmMissingConfidenceThreshold"] = float(imported_value)
        return merged
