from __future__ import annotations

import os
from dataclasses import asdict, dataclass
from pathlib import Path

from dotenv import load_dotenv


load_dotenv(Path(__file__).resolve().parent / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


@dataclass(slots=True)
class Settings:
    service_name: str = os.getenv("ERHU_SERVICE_NAME", "ai-erhu-analyzer")
    host: str = os.getenv("ERHU_HOST", "0.0.0.0")
    port: int = int(os.getenv("ERHU_PORT", "8000"))
    data_root: str = os.getenv("ERHU_DATA_ROOT", str((Path(__file__).resolve().parent.parent / "data").resolve()))
    target_sample_rate: int = int(os.getenv("ERHU_TARGET_SAMPLE_RATE", "16000"))
    pitch_hop_ms: int = int(os.getenv("ERHU_PITCH_HOP_MS", "10"))
    onset_hop_length: int = int(os.getenv("ERHU_ONSET_HOP_LENGTH", "256"))
    min_confidence: float = float(os.getenv("ERHU_MIN_CONFIDENCE", "0.6"))
    uncertain_confidence: float = float(os.getenv("ERHU_UNCERTAIN_CONFIDENCE", "0.63"))
    stable_region_start_ratio: float = float(os.getenv("ERHU_STABLE_REGION_START_RATIO", "0.2"))
    stable_region_end_ratio: float = float(os.getenv("ERHU_STABLE_REGION_END_RATIO", "0.82"))
    expressive_core_start_ratio: float = float(os.getenv("ERHU_EXPRESSIVE_CORE_START_RATIO", "0.3"))
    expressive_core_end_ratio: float = float(os.getenv("ERHU_EXPRESSIVE_CORE_END_RATIO", "0.72"))
    stable_note_min_frames: int = int(os.getenv("ERHU_STABLE_NOTE_MIN_FRAMES", "3"))
    base_pitch_tolerance_cents: float = float(os.getenv("ERHU_BASE_PITCH_TOLERANCE_CENTS", "22"))
    vibrato_spread_threshold_cents: float = float(os.getenv("ERHU_VIBRATO_SPREAD_THRESHOLD_CENTS", "26"))
    vibrato_tolerance_bonus_cents: float = float(os.getenv("ERHU_VIBRATO_TOLERANCE_BONUS_CENTS", "10"))
    vibrato_lowpass_cutoff_hz: float = float(os.getenv("ERHU_VIBRATO_LOWPASS_CUTOFF_HZ", "2.0"))
    vibrato_max_amplitude_cents: float = float(os.getenv("ERHU_VIBRATO_MAX_AMPLITUDE_CENTS", "50"))
    vibrato_min_amplitude_cents: float = float(os.getenv("ERHU_VIBRATO_MIN_AMPLITUDE_CENTS", "8"))
    vibrato_min_zero_crossings: int = int(os.getenv("ERHU_VIBRATO_MIN_ZERO_CROSSINGS", "4"))
    glide_entry_threshold_cents: float = float(os.getenv("ERHU_GLIDE_ENTRY_THRESHOLD_CENTS", "24"))
    glide_tolerance_bonus_cents: float = float(os.getenv("ERHU_GLIDE_TOLERANCE_BONUS_CENTS", "14"))
    glide_derivative_threshold_cents_per_ms: float = float(os.getenv("ERHU_GLIDE_DERIVATIVE_THRESHOLD_CENTS_PER_MS", "1.0"))
    glide_min_duration_ms: float = float(os.getenv("ERHU_GLIDE_MIN_DURATION_MS", "30"))
    max_pitch_tolerance_cents: float = float(os.getenv("ERHU_MAX_PITCH_TOLERANCE_CENTS", "45"))
    glide_relief_max_cents: float = float(os.getenv("ERHU_GLIDE_RELIEF_MAX_CENTS", "9"))
    vibrato_relief_max_cents: float = float(os.getenv("ERHU_VIBRATO_RELIEF_MAX_CENTS", "7"))
    trill_jump_threshold_cents: float = float(os.getenv("ERHU_TRILL_JUMP_THRESHOLD_CENTS", "50"))
    trill_cluster_spread_cents: float = float(os.getenv("ERHU_TRILL_CLUSTER_SPREAD_CENTS", "35"))
    trill_min_switch_count: int = int(os.getenv("ERHU_TRILL_MIN_SWITCH_COUNT", "3"))
    pluck_entry_threshold_cents: float = float(os.getenv("ERHU_PLUCK_ENTRY_THRESHOLD_CENTS", "70"))
    pluck_relief_max_cents: float = float(os.getenv("ERHU_PLUCK_RELIEF_MAX_CENTS", "6"))
    technique_uncertain_spread_cents: float = float(os.getenv("ERHU_TECHNIQUE_UNCERTAIN_SPREAD_CENTS", "44"))
    technique_uncertain_confidence: float = float(os.getenv("ERHU_TECHNIQUE_UNCERTAIN_CONFIDENCE", "0.68"))
    base_rhythm_tolerance_ms: float = float(os.getenv("ERHU_BASE_RHYTHM_TOLERANCE_MS", "75"))
    rhythm_duration_ratio_tolerance: float = float(os.getenv("ERHU_RHYTHM_DURATION_RATIO_TOLERANCE", "0.30"))
    rhythm_measure_trend_ms: float = float(os.getenv("ERHU_RHYTHM_MEASURE_TREND_MS", "50"))
    rhythm_measure_instability_ms: float = float(os.getenv("ERHU_RHYTHM_MEASURE_INSTABILITY_MS", "36"))
    rhythm_missing_confidence: float = float(os.getenv("ERHU_RHYTHM_MISSING_CONFIDENCE", "0.12"))
    pitch_penalty_median_weight: float = float(os.getenv("ERHU_PITCH_PENALTY_MEDIAN_WEIGHT", "1.10"))
    pitch_penalty_issue_weight: float = float(os.getenv("ERHU_PITCH_PENALTY_ISSUE_WEIGHT", "1.20"))
    pitch_penalty_uncertain_weight: float = float(os.getenv("ERHU_PITCH_PENALTY_UNCERTAIN_WEIGHT", "0.20"))
    rhythm_penalty_median_weight: float = float(os.getenv("ERHU_RHYTHM_PENALTY_MEDIAN_WEIGHT", "0.35"))
    rhythm_penalty_issue_weight: float = float(os.getenv("ERHU_RHYTHM_PENALTY_ISSUE_WEIGHT", "1.00"))
    rhythm_penalty_measure_weight: float = float(os.getenv("ERHU_RHYTHM_PENALTY_MEASURE_WEIGHT", "1.50"))
    student_display_score_scale: float = float(os.getenv("ERHU_STUDENT_DISPLAY_SCORE_SCALE", "0.75"))
    student_display_score_bias: float = float(os.getenv("ERHU_STUDENT_DISPLAY_SCORE_BIAS", "18"))
    student_display_score_confidence_weight: float = float(os.getenv("ERHU_STUDENT_DISPLAY_SCORE_CONFIDENCE_WEIGHT", "8"))
    separation_harmonics: int = int(os.getenv("ERHU_SEPARATION_HARMONICS", "6"))
    separation_bandwidth_cents: float = float(os.getenv("ERHU_SEPARATION_BANDWIDTH_CENTS", "55"))
    separation_pitch_confidence: float = float(os.getenv("ERHU_SEPARATION_PITCH_CONFIDENCE", "0.45"))
    separation_residual_mix: float = float(os.getenv("ERHU_SEPARATION_RESIDUAL_MIX", "0.08"))
    separation_output_blend: float = float(os.getenv("ERHU_SEPARATION_OUTPUT_BLEND", "0.9"))
    separation_auto_confidence_threshold: float = float(os.getenv("ERHU_SEPARATION_AUTO_CONFIDENCE_THRESHOLD", "0.4"))
    separation_auto_score_band_bonus: float = float(os.getenv("ERHU_SEPARATION_AUTO_SCORE_BAND_BONUS", "0.12"))
    enable_clip_feature_cache: bool = env_bool("ERHU_ENABLE_CLIP_FEATURE_CACHE", True)
    clip_feature_cache_version: str = os.getenv("ERHU_CLIP_FEATURE_CACHE_VERSION", "v14-windowed-analysis")
    ranking_pitch_hop_ms: int = int(os.getenv("ERHU_RANKING_PITCH_HOP_MS", "25"))
    ranking_long_audio_seconds: float = float(os.getenv("ERHU_RANKING_LONG_AUDIO_SECONDS", "240"))
    ranking_long_pitch_hop_ms: int = int(os.getenv("ERHU_RANKING_LONG_PITCH_HOP_MS", "55"))
    ranking_very_long_audio_seconds: float = float(os.getenv("ERHU_RANKING_VERY_LONG_AUDIO_SECONDS", "420"))
    ranking_very_long_pitch_hop_ms: int = int(os.getenv("ERHU_RANKING_VERY_LONG_PITCH_HOP_MS", "85"))
    ranking_use_score_onsets_only: bool = env_bool("ERHU_RANKING_USE_SCORE_ONSETS_ONLY", True)
    ranking_max_score_notes: int = int(os.getenv("ERHU_RANKING_MAX_SCORE_NOTES", "320"))
    ranking_dense_section_note_threshold: int = int(os.getenv("ERHU_RANKING_DENSE_SECTION_NOTE_THRESHOLD", "96"))
    ranking_max_section_score_notes: int = int(os.getenv("ERHU_RANKING_MAX_SECTION_SCORE_NOTES", "72"))
    ranking_preprocess_min_duration_seconds: float = float(os.getenv("ERHU_RANKING_PREPROCESS_MIN_DURATION_SECONDS", "45"))
    ranking_preprocess_sample_rate: int = int(os.getenv("ERHU_RANKING_PREPROCESS_SAMPLE_RATE", "16000"))
    ranking_preprocess_n_fft: int = int(os.getenv("ERHU_RANKING_PREPROCESS_NFFT", "1024"))
    ranking_preprocess_harmonics: int = int(os.getenv("ERHU_RANKING_PREPROCESS_HARMONICS", "4"))
    detection_window_start_padding_seconds: float = float(os.getenv("ERHU_DETECTION_WINDOW_START_PADDING_SECONDS", "0.35"))
    detection_window_end_padding_seconds: float = float(os.getenv("ERHU_DETECTION_WINDOW_END_PADDING_SECONDS", "0.85"))
    detection_window_min_duration_seconds: float = float(os.getenv("ERHU_DETECTION_WINDOW_MIN_DURATION_SECONDS", "8"))
    detection_window_max_duration_seconds: float = float(os.getenv("ERHU_DETECTION_WINDOW_MAX_DURATION_SECONDS", "50"))
    detection_window_score_duration_ratio: float = float(os.getenv("ERHU_DETECTION_WINDOW_SCORE_DURATION_RATIO", "0.92"))
    madmom_relaxed_onset_quantile: float = float(os.getenv("ERHU_MADMOM_RELAXED_ONSET_QUANTILE", "0.88"))
    madmom_relaxed_onset_scale: float = float(os.getenv("ERHU_MADMOM_RELAXED_ONSET_SCALE", "0.58"))
    madmom_relaxed_onset_min_threshold: float = float(os.getenv("ERHU_MADMOM_RELAXED_ONSET_MIN_THRESHOLD", "0.18"))
    madmom_relaxed_onset_min_spacing_ms: float = float(os.getenv("ERHU_MADMOM_RELAXED_ONSET_MIN_SPACING_MS", "55"))
    madmom_relaxed_onset_min_count_ratio: float = float(os.getenv("ERHU_MADMOM_RELAXED_ONSET_MIN_COUNT_RATIO", "0.18"))
    analysis_stability_retry_enabled: bool = env_bool("ERHU_ANALYSIS_STABILITY_RETRY_ENABLED", True)
    analysis_stability_retry_max_retries: int = int(os.getenv("ERHU_ANALYSIS_STABILITY_RETRY_MAX_RETRIES", "3"))
    analysis_stability_pitch_threshold: float = float(os.getenv("ERHU_ANALYSIS_STABILITY_PITCH_THRESHOLD", "70"))
    analysis_stability_min_rhythm_score: float = float(os.getenv("ERHU_ANALYSIS_STABILITY_MIN_RHYTHM_SCORE", "85"))
    analysis_stability_max_pitch_issues: int = int(os.getenv("ERHU_ANALYSIS_STABILITY_MAX_PITCH_ISSUES", "1"))
    analysis_stability_min_uncertain_pitch: int = int(os.getenv("ERHU_ANALYSIS_STABILITY_MIN_UNCERTAIN_PITCH", "5"))
    enable_torchcrepe: bool = env_bool("ERHU_ENABLE_TORCHCREPE", False)
    enable_madmom: bool = env_bool("ERHU_ENABLE_MADMOM", True)
    enable_librosa_decode: bool = env_bool("ERHU_ENABLE_LIBROSA_DECODE", False)
    madmom_fps: int = int(os.getenv("ERHU_MADMOM_FPS", "100"))
    audiveris_cli: str = os.getenv("ERHU_AUDIVERIS_CLI", "")
    audiveris_timeout_seconds: int = int(os.getenv("ERHU_AUDIVERIS_TIMEOUT_SECONDS", "180"))
    omr_preview_pages: int = int(os.getenv("ERHU_OMR_PREVIEW_PAGES", "3"))
    omr_page_max_pixels: int = int(os.getenv("ERHU_OMR_PAGE_MAX_PIXELS", "26000000"))
    omr_render_dpi: int = int(os.getenv("ERHU_OMR_RENDER_DPI", "300"))
    omr_render_min_dpi: int = int(os.getenv("ERHU_OMR_RENDER_MIN_DPI", "220"))
    omr_whole_pdf_max_pages: int = int(os.getenv("ERHU_OMR_WHOLE_PDF_MAX_PAGES", "6"))
    omr_pagewise_workers: int = int(os.getenv("ERHU_OMR_PAGEWISE_WORKERS", "3"))
    omr_page_cache_version: str = os.getenv("ERHU_OMR_PAGE_CACHE_VERSION", "v1-page-cache")
    ffmpeg_path: str = os.getenv("ERHU_FFMPEG_PATH", "")
    fallback_issue_limit: int = int(os.getenv("ERHU_FALLBACK_ISSUE_LIMIT", "4"))
    piano_onset_suppression_strength: float = float(os.getenv("ERHU_PIANO_ONSET_SUPPRESSION_STRENGTH", "0.28"))
    piano_onset_decay_ms: float = float(os.getenv("ERHU_PIANO_ONSET_DECAY_MS", "160"))

    def public_dict(self) -> dict[str, object]:
        return asdict(self)


settings = Settings()
