export const ERHU_STUDY_PIECES = [
  {
    pieceId: "d-major-scale-fragment",
    title: "D调一把位音阶片段",
    composer: "研究任务曲目 A",
    targetSkills: ["音准稳定", "换弦控制", "均匀拍感"],
    difficulty: "高校二胡专业基础段",
    sections: [
      {
        sectionId: "section-a",
        title: "上行音阶与长音保持",
        tempo: 72,
        meter: "4/4",
        demoAudio: "",
        notes: [
          { noteId: "a-m1-n1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 62 },
          { noteId: "a-m1-n2", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 64 },
          { noteId: "a-m1-n3", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 66 },
          { noteId: "a-m1-n4", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 67 },
          { noteId: "a-m2-n1", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 69 },
          { noteId: "a-m2-n2", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 71 },
          { noteId: "a-m2-n3", measureIndex: 2, beatStart: 2, beatDuration: 2, midiPitch: 74 },
          { noteId: "a-m3-n1", measureIndex: 3, beatStart: 0, beatDuration: 2, midiPitch: 74 },
          { noteId: "a-m3-n2", measureIndex: 3, beatStart: 2, beatDuration: 1, midiPitch: 71 },
          { noteId: "a-m3-n3", measureIndex: 3, beatStart: 3, beatDuration: 1, midiPitch: 69 },
          { noteId: "a-m4-n1", measureIndex: 4, beatStart: 0, beatDuration: 1, midiPitch: 67 },
          { noteId: "a-m4-n2", measureIndex: 4, beatStart: 1, beatDuration: 1, midiPitch: 66 },
          { noteId: "a-m4-n3", measureIndex: 4, beatStart: 2, beatDuration: 1, midiPitch: 64 },
          { noteId: "a-m4-n4", measureIndex: 4, beatStart: 3, beatDuration: 1, midiPitch: 62 },
        ],
      },
      {
        sectionId: "section-b",
        title: "附点与切分节奏片段",
        tempo: 80,
        meter: "4/4",
        demoAudio: "",
        notes: [
          { noteId: "b-m1-n1", measureIndex: 1, beatStart: 0, beatDuration: 1.5, midiPitch: 69 },
          { noteId: "b-m1-n2", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 71 },
          { noteId: "b-m1-n3", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 72 },
          { noteId: "b-m1-n4", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 74 },
          { noteId: "b-m2-n1", measureIndex: 2, beatStart: 0, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "b-m2-n2", measureIndex: 2, beatStart: 0.5, beatDuration: 1.5, midiPitch: 72 },
          { noteId: "b-m2-n3", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 71 },
          { noteId: "b-m2-n4", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 69 },
          { noteId: "b-m3-n1", measureIndex: 3, beatStart: 0, beatDuration: 1, midiPitch: 67 },
          { noteId: "b-m3-n2", measureIndex: 3, beatStart: 1, beatDuration: 1, midiPitch: 69 },
          { noteId: "b-m3-n3", measureIndex: 3, beatStart: 2, beatDuration: 2, midiPitch: 71 },
        ],
      },
    ],
  },
  {
    pieceId: "pentatonic-lyrical-study",
    title: "五声音阶旋律练习",
    composer: "研究任务曲目 B",
    targetSkills: ["连贯句法", "慢速节奏控制", "音高稳定区"],
    difficulty: "高校二胡专业中级段",
    sections: [
      {
        sectionId: "section-a",
        title: "歌唱性慢板句",
        tempo: 60,
        meter: "4/4",
        demoAudio: "",
        notes: [
          { noteId: "c-m1-n1", measureIndex: 1, beatStart: 0, beatDuration: 2, midiPitch: 67 },
          { noteId: "c-m1-n2", measureIndex: 1, beatStart: 2, beatDuration: 2, midiPitch: 69 },
          { noteId: "c-m2-n1", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 71 },
          { noteId: "c-m2-n2", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 74 },
          { noteId: "c-m2-n3", measureIndex: 2, beatStart: 2, beatDuration: 2, midiPitch: 76 },
          { noteId: "c-m3-n1", measureIndex: 3, beatStart: 0, beatDuration: 1, midiPitch: 74 },
          { noteId: "c-m3-n2", measureIndex: 3, beatStart: 1, beatDuration: 1, midiPitch: 71 },
          { noteId: "c-m3-n3", measureIndex: 3, beatStart: 2, beatDuration: 2, midiPitch: 69 },
          { noteId: "c-m4-n1", measureIndex: 4, beatStart: 0, beatDuration: 4, midiPitch: 67 },
        ],
      },
    ],
  },
  {
    pieceId: "bowing-rhythm-cell",
    title: "均分节奏与重音控制",
    composer: "研究任务曲目 C",
    targetSkills: ["节奏稳定", "重音清晰", "快速定位错误音"],
    difficulty: "高校二胡专业节奏控制段",
    sections: [
      {
        sectionId: "section-a",
        title: "八分音符均分练习",
        tempo: 96,
        meter: "2/4",
        demoAudio: "",
        notes: [
          { noteId: "d-m1-n1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 62 },
          { noteId: "d-m1-n2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 64 },
          { noteId: "d-m1-n3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 66 },
          { noteId: "d-m1-n4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "d-m2-n1", measureIndex: 2, beatStart: 0, beatDuration: 0.5, midiPitch: 69 },
          { noteId: "d-m2-n2", measureIndex: 2, beatStart: 0.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "d-m2-n3", measureIndex: 2, beatStart: 1, beatDuration: 0.5, midiPitch: 66 },
          { noteId: "d-m2-n4", measureIndex: 2, beatStart: 1.5, beatDuration: 0.5, midiPitch: 64 },
          { noteId: "d-m3-n1", measureIndex: 3, beatStart: 0, beatDuration: 0.5, midiPitch: 62 },
          { noteId: "d-m3-n2", measureIndex: 3, beatStart: 0.5, beatDuration: 0.5, midiPitch: 64 },
          { noteId: "d-m3-n3", measureIndex: 3, beatStart: 1, beatDuration: 0.5, midiPitch: 66 },
          { noteId: "d-m3-n4", measureIndex: 3, beatStart: 1.5, beatDuration: 0.5, midiPitch: 69 },
        ],
      },
    ],
  },
  {
    pieceId: "taohuawu-test-fragment",
    title: "\u6843\u82b1\u575e\uff08\u6d4b\u8bd5\u7247\u6bb5\uff09",
    composer: "\u9646\u8f76\u6587 / PDF \u624b\u5de5\u5f55\u8c31",
    targetSkills: ["rubato-entry", "mixed-audio-alignment", "phrase-intonation", "segment-identification"],
    difficulty: "\u4e8c\u80e1\u4e0e\u94a2\u7434\u6df7\u5408\u5f55\u97f3\u5207\u7247\u4e0e\u6bb5\u843d\u6d4b\u8bd5",
    coverageMode: "major-sections",
    sourceAudio: "data/test_audio_mix.mp3",
    sourceScore: "data/test_score.pdf",
    wholePieceExportReady: true,
    sections: [
      {
        sectionId: "entry-head",
        title: "\u5165\u53e5\u52a8\u673a A",
        tempo: 72,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 1,
        researchWindowHints: [8, 10, 12],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 14,
          extraRhythmToleranceMs: 18,
          lowSeparationThreshold: 0.74,
          lowSeparationExtraToleranceCents: 18,
          lowSeparationExtraRhythmToleranceMs: 14,
          extraDurationToleranceRatio: 0.12,
          measureTrendToleranceMs: 82,
          measureInstabilityToleranceMs: 56,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1200,
          lowConfidenceRhythmReviewThresholdMs: 2200,
          octaveFlexMaxSteps: 3,
          coarseScoreReviewThresholdCents: 2800,
          isolatedPitchReviewThresholdCents: 2200,
          scoreGuideGain: 0.34,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-h1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 78 },
          { noteId: "tw-h2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-h3", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-h4", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 79 },
        ],
      },
      {
        sectionId: "entry-phrase",
        title: "\u5f15\u5b50\u540e\u5165\u53e5\u7247\u6bb5",
        tempo: 72,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 2,
        researchWindowHints: [8, 10, 12, 14],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 14,
          extraRhythmToleranceMs: 22,
          lowSeparationThreshold: 0.8,
          lowSeparationExtraToleranceCents: 18,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.16,
          measureTrendToleranceMs: 88,
          measureInstabilityToleranceMs: 60,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1400,
          lowConfidenceRhythmReviewThresholdMs: 2600,
          octaveFlexMaxSteps: 3,
          coarseScoreReviewThresholdCents: 3400,
          isolatedPitchReviewThresholdCents: 3400,
          scoreGuideGain: 0.34,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-m1-n1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 78 },
          { noteId: "tw-m1-n2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-m1-n3", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-m1-n4", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-m1-n5", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-m1-n6", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-m2-n1", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 73 },
          { noteId: "tw-m2-n2", measureIndex: 2, beatStart: 1, beatDuration: 2, midiPitch: 71 },
        ],
      },
      {
        sectionId: "entry-tail",
        title: "\u5165\u53e5\u5c3e\u58f0",
        tempo: 72,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 3,
        researchWindowHints: [12, 14, 16],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          extraRhythmToleranceMs: 22,
          lowSeparationThreshold: 0.82,
          lowSeparationExtraToleranceCents: 14,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.16,
          measureTrendToleranceMs: 90,
          measureInstabilityToleranceMs: 60,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1500,
          lowConfidenceRhythmReviewThresholdMs: 2600,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 1100,
          isolatedPitchReviewThresholdCents: 900,
          scoreGuideGain: 0.32,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-t1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-t2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-t3", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-t4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 73 },
          { noteId: "tw-t5", measureIndex: 1, beatStart: 3, beatDuration: 2, midiPitch: 71 },
        ],
      },
      {
        sectionId: "answer-phrase",
        title: "\u5e94\u7b54\u53e5",
        tempo: 72,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 4,
        researchWindowHints: [16, 18, 20],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 12,
          extraRhythmToleranceMs: 22,
          lowSeparationThreshold: 0.8,
          lowSeparationExtraToleranceCents: 18,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.16,
          measureTrendToleranceMs: 90,
          measureInstabilityToleranceMs: 60,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1400,
          lowConfidenceRhythmReviewThresholdMs: 2600,
          octaveFlexMaxSteps: 3,
          coarseScoreReviewThresholdCents: 1500,
          isolatedPitchReviewThresholdCents: 1500,
          scoreGuideGain: 0.34,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-a1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 78 },
          { noteId: "tw-a2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-a3", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-a4", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 68 },
          { noteId: "tw-a5", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 69 },
          { noteId: "tw-a6", measureIndex: 1, beatStart: 3, beatDuration: 1.5, midiPitch: 71 },
        ],
      },
      {
        sectionId: "answer-resolution",
        title: "\u5e94\u7b54\u6536\u675f",
        tempo: 68,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 5,
        researchWindowHints: [18, 20, 22],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          extraRhythmToleranceMs: 18,
          lowSeparationThreshold: 0.8,
          lowSeparationExtraToleranceCents: 16,
          lowSeparationExtraRhythmToleranceMs: 14,
          extraDurationToleranceRatio: 0.14,
          measureTrendToleranceMs: 84,
          measureInstabilityToleranceMs: 56,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1200,
          lowConfidenceRhythmReviewThresholdMs: 2200,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 1200,
          isolatedPitchReviewThresholdCents: 900,
          scoreGuideGain: 0.32,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-r1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-r2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-r3", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 71 },
          { noteId: "tw-r4", measureIndex: 1, beatStart: 2, beatDuration: 2, midiPitch: 69 },
        ],
      },
      {
        sectionId: "bridge-call",
        title: "\u6865\u63a5\u53e5",
        tempo: 66,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 6,
        researchWindowHints: [22, 24, 26, 28],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 12,
          extraRhythmToleranceMs: 18,
          lowSeparationThreshold: 0.74,
          lowSeparationExtraToleranceCents: 18,
          lowSeparationExtraRhythmToleranceMs: 14,
          extraDurationToleranceRatio: 0.12,
          measureTrendToleranceMs: 82,
          measureInstabilityToleranceMs: 56,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1200,
          lowConfidenceRhythmReviewThresholdMs: 2200,
          octaveFlexMaxSteps: 3,
          coarseScoreReviewThresholdCents: 2200,
          isolatedPitchReviewThresholdCents: 1600,
          scoreGuideGain: 0.34,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-b1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 78 },
          { noteId: "tw-b2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-b3", measureIndex: 1, beatStart: 1, beatDuration: 1.5, midiPitch: 74 },
          { noteId: "tw-b4", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-b5", measureIndex: 1, beatStart: 3, beatDuration: 1.5, midiPitch: 74 },
        ],
      },
      {
        sectionId: "sustain-trill",
        title: "\u957f\u97f3\u4e0e\u9894\u6307",
        tempo: 64,
        meter: "3/4",
        demoAudio: "",
        sequenceIndex: 7,
        researchWindowHints: [28, 30, 32, 34],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          extraRhythmToleranceMs: 42,
          lowSeparationThreshold: 0.72,
          lowSeparationExtraToleranceCents: 12,
          lowSeparationExtraRhythmToleranceMs: 28,
          extraDurationToleranceRatio: 0.24,
          measureTrendToleranceMs: 2800,
          measureInstabilityToleranceMs: 96,
          rhythmMissingConfidenceThreshold: 0.05,
          coarseRhythmReviewThresholdMs: 3200,
          lowConfidenceRhythmReviewThresholdMs: 4200,
          octaveFlexMaxSteps: 3,
          coarseScoreReviewThresholdCents: 2600,
          isolatedPitchReviewThresholdCents: 2600,
          scoreGuideGain: 0.36,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-s1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-s2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-s3", measureIndex: 1, beatStart: 1, beatDuration: 3, midiPitch: 74 },
        ],
      },
      {
        sectionId: "held-trill-return",
        title: "\u9ad8\u97f3\u98a4\u97f3\u56de\u5f52",
        tempo: 84,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 8,
        researchWindowHints: [40, 42, 44],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 16,
          extraRhythmToleranceMs: 18,
          lowSeparationThreshold: 0.8,
          lowSeparationExtraToleranceCents: 24,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.14,
          measureTrendToleranceMs: 84,
          measureInstabilityToleranceMs: 58,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1200,
          lowConfidenceRhythmReviewThresholdMs: 2200,
          octaveFlexMaxSteps: 4,
          coarseScoreReviewThresholdCents: 3400,
          isolatedPitchReviewThresholdCents: 3400,
          scoreGuideGain: 0.4,
          scoreGuideBandwidthCents: 30,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-hr1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 83 },
          { noteId: "tw-hr2", measureIndex: 1, beatStart: 0.5, beatDuration: 1.5, midiPitch: 84 },
          { noteId: "tw-hr3", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-hr4", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 84 },
        ],
      },
      {
        sectionId: "lyrical-turn-a",
        title: "\u6292\u60c5\u56de\u8f6c A",
        tempo: 96,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 9,
        researchWindowHints: [50, 52, 54],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 14,
          extraRhythmToleranceMs: 24,
          lowSeparationThreshold: 0.78,
          lowSeparationExtraToleranceCents: 20,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.16,
          measureTrendToleranceMs: 96,
          measureInstabilityToleranceMs: 64,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1400,
          lowConfidenceRhythmReviewThresholdMs: 2800,
          octaveFlexMaxSteps: 4,
          coarseScoreReviewThresholdCents: 3400,
          isolatedPitchReviewThresholdCents: 3400,
          scoreGuideGain: 0.36,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-l1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-l2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-l3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-l4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-l5", measureIndex: 1, beatStart: 3, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-l6", measureIndex: 1, beatStart: 3.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-l7", measureIndex: 2, beatStart: 0, beatDuration: 2, midiPitch: 79 },
        ],
      },
      {
        sectionId: "middle-sequence",
        title: "\u4e2d\u6bb5\u5e94\u7b54\u5e8f\u5217",
        tempo: 96,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 10,
        researchWindowHints: [60, 62, 64],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          extraRhythmToleranceMs: 20,
          lowSeparationThreshold: 0.68,
          lowSeparationExtraToleranceCents: 14,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.14,
          measureTrendToleranceMs: 90,
          measureInstabilityToleranceMs: 60,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1100,
          lowConfidenceRhythmReviewThresholdMs: 2400,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 1200,
          isolatedPitchReviewThresholdCents: 900,
          scoreGuideGain: 0.32,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-ms1", measureIndex: 1, beatStart: 0, beatDuration: 2, midiPitch: 74 },
          { noteId: "tw-ms2", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-ms3", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-ms4", measureIndex: 1, beatStart: 3, beatDuration: 0.5, midiPitch: 72 },
          { noteId: "tw-ms5", measureIndex: 1, beatStart: 3.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-ms6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-ms7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-ms8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-ms9", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 79 },
        ],
      },
      {
        sectionId: "bridge-rise",
        title: "\u6865\u63a5\u4e0a\u884c",
        tempo: 96,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 11,
        researchWindowHints: [70, 72, 74],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 6,
          lowSeparationThreshold: 0.62,
          lowSeparationExtraToleranceCents: 8,
          octaveFlexMaxSteps: 1,
          coarseScoreReviewThresholdCents: 500,
          scoreGuideGain: 0.24,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.7,
        },
        notes: [
          { noteId: "tw-br1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 72 },
          { noteId: "tw-br2", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-br3", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-br4", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-br5", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 72 },
          { noteId: "tw-br6", measureIndex: 2, beatStart: 1, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-br7", measureIndex: 2, beatStart: 1.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-br8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 79 },
        ],
      },
      {
        sectionId: "run-up-gliss",
        title: "\u6ed1\u97f3\u4e0a\u884c\u53e5",
        tempo: 104,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 12,
        researchWindowHints: [82, 84, 86],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 16,
          extraRhythmToleranceMs: 26,
          lowSeparationThreshold: 0.7,
          lowSeparationExtraToleranceCents: 18,
          lowSeparationExtraRhythmToleranceMs: 20,
          extraDurationToleranceRatio: 0.18,
          measureTrendToleranceMs: 110,
          measureInstabilityToleranceMs: 72,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1800,
          lowConfidenceRhythmReviewThresholdMs: 3200,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 2200,
          isolatedPitchReviewThresholdCents: 2200,
          scoreGuideGain: 0.22,
          scoreGuideBandwidthCents: 44,
          scoreGuideConfidenceFloor: 0.7,
        },
        notes: [
          { noteId: "tw-rg1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 62 },
          { noteId: "tw-rg2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 64 },
          { noteId: "tw-rg3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-rg4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 69 },
          { noteId: "tw-rg5", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 72 },
          { noteId: "tw-rg6", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-rg7", measureIndex: 1, beatStart: 3, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-rg8", measureIndex: 1, beatStart: 3.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-rg9", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 79 },
        ],
      },
        {
          sectionId: "answer-loop",
          title: "\u5faa\u73af\u5e94\u7b54\u53e5",
          tempo: 96,
          meter: "4/4",
          demoAudio: "",
          sequenceIndex: 13,
          researchWindowHints: [94, 96, 98],
          calibrationProfile: {
            scoreCoarse: true,
            preferScoreBoundaries: true,
            extraPitchToleranceCents: 10,
            extraRhythmToleranceMs: 22,
            lowSeparationExtraRhythmToleranceMs: 18,
            extraDurationToleranceRatio: 0.14,
            measureTrendToleranceMs: 82,
            measureInstabilityToleranceMs: 56,
            rhythmMissingConfidenceThreshold: 0.06,
            coarseRhythmReviewThresholdMs: 900,
            lowConfidenceRhythmReviewThresholdMs: 3400,
            lowSeparationThreshold: 0.78,
            lowSeparationExtraToleranceCents: 12,
            octaveFlexMaxSteps: 2,
            coarseScoreReviewThresholdCents: 620,
            isolatedPitchReviewThresholdCents: 220,
            scoreGuideGain: 0.36,
            scoreGuideBandwidthCents: 32,
            scoreGuideConfidenceFloor: 0.74,
          },
          notes: [
            { noteId: "tw-al1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 72 },
            { noteId: "tw-al2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 74 },
            { noteId: "tw-al3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-al4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-al5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-al6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-al7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-al8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 81 },
        ],
      },
      {
        sectionId: "recap-call",
        title: "\u518d\u73b0\u53ec\u5524\u53e5",
        tempo: 96,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 14,
        researchWindowHints: [106, 108, 110],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 6,
          lowSeparationThreshold: 0.6,
          lowSeparationExtraToleranceCents: 8,
          octaveFlexMaxSteps: 1,
          coarseScoreReviewThresholdCents: 500,
          scoreGuideGain: 0.22,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.7,
        },
        notes: [
          { noteId: "tw-rc1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 72 },
          { noteId: "tw-rc2", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-rc3", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-rc4", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-rc5", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-rc6", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-rc7", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 72 },
          { noteId: "tw-rc8", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 79 },
        ],
      },
      {
        sectionId: "closing-climb",
        title: "\u7ed3\u5c3e\u4e0a\u884c\u4e0e\u518d\u5f52",
        tempo: 104,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 15,
        researchWindowHints: [116, 118, 120],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 8,
          extraRhythmToleranceMs: 30,
          lowSeparationThreshold: 0.72,
          lowSeparationExtraToleranceCents: 10,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.22,
          measureTrendToleranceMs: 120,
          measureInstabilityToleranceMs: 80,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 2200,
          lowConfidenceRhythmReviewThresholdMs: 3600,
          octaveFlexMaxSteps: 1,
          coarseScoreReviewThresholdCents: 520,
          isolatedPitchReviewThresholdCents: 320,
          scoreGuideGain: 0.28,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-cc1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-cc2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-cc3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-cc4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-cc5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-cc6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-cc7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-cc8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-cc9", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 76 },
        ],
      },
      {
        sectionId: "modulation-call",
        title: "\u8f6c\u8c03\u53ec\u5524\u53e5",
        tempo: 108,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 16,
        researchWindowHints: [130, 132, 134],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 16,
          extraRhythmToleranceMs: 16,
          lowSeparationThreshold: 0.8,
          lowSeparationExtraToleranceCents: 24,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.12,
          measureTrendToleranceMs: 84,
          measureInstabilityToleranceMs: 58,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1200,
          lowConfidenceRhythmReviewThresholdMs: 2200,
          octaveFlexMaxSteps: 4,
          coarseScoreReviewThresholdCents: 3400,
          isolatedPitchReviewThresholdCents: 3400,
          uncertainPenaltyScale: 0,
          scoreGuideGain: 0.4,
          scoreGuideBandwidthCents: 32,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-mc1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 72 },
          { noteId: "tw-mc2", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-mc3", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-mc4", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-mc5", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 72 },
          { noteId: "tw-mc6", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-mc7", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-mc8", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 72 },
        ],
      },
      {
        sectionId: "triplet-dialogue",
        title: "\u4e09\u8fde\u97f3\u5bf9\u8bdd",
        tempo: 112,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 17,
        researchWindowHints: [142, 144, 146],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 8,
          extraRhythmToleranceMs: 18,
          lowSeparationThreshold: 0.64,
          lowSeparationExtraToleranceCents: 8,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.12,
          measureTrendToleranceMs: 100,
          measureInstabilityToleranceMs: 64,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1400,
          lowConfidenceRhythmReviewThresholdMs: 2600,
          octaveFlexMaxSteps: 1,
          coarseScoreReviewThresholdCents: 520,
          isolatedPitchReviewThresholdCents: 280,
          uncertainPenaltyScale: 0,
          rhythmIssuePenaltyScale: 0.5,
          measureFindingPenaltyScale: 0.4,
          scoreGuideGain: 0.28,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-td1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 64 },
          { noteId: "tw-td2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-td3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 71 },
          { noteId: "tw-td4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-td5", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 71 },
          { noteId: "tw-td6", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-td7", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-td8", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 76 },
        ],
      },
        {
          sectionId: "con-brio-entry",
          title: "Con brio \u5165\u53e5",
          tempo: 132,
          meter: "4/4",
          demoAudio: "",
          sequenceIndex: 18,
          researchWindowHints: [154, 156, 158],
          calibrationProfile: {
            scoreCoarse: true,
            preferScoreBoundaries: true,
            extraPitchToleranceCents: 10,
            extraRhythmToleranceMs: 16,
            lowSeparationExtraRhythmToleranceMs: 12,
            extraDurationToleranceRatio: 0.1,
            measureTrendToleranceMs: 72,
            measureInstabilityToleranceMs: 50,
            rhythmMissingConfidenceThreshold: 0.08,
            coarseRhythmReviewThresholdMs: 850,
            lowConfidenceRhythmReviewThresholdMs: 1600,
            lowSeparationThreshold: 0.62,
            lowSeparationExtraToleranceCents: 12,
            octaveFlexMaxSteps: 2,
            coarseScoreReviewThresholdCents: 620,
            isolatedPitchReviewThresholdCents: 240,
            scoreGuideGain: 0.38,
            scoreGuideBandwidthCents: 30,
            scoreGuideConfidenceFloor: 0.74,
          },
          notes: [
            { noteId: "tw-cb1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 85 },
            { noteId: "tw-cb2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 84 },
            { noteId: "tw-cb3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-cb4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 84 },
          { noteId: "tw-cb5", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-cb6", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-cb7", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-cb8", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 81 },
        ],
      },
      {
        sectionId: "sharp-mode-climax",
        title: "\u5347\u8bb0\u53f7\u8c03\u6027\u9ad8\u6f6e",
        tempo: 132,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 19,
        researchWindowHints: [166, 168, 170],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 14,
          extraRhythmToleranceMs: 14,
          lowSeparationThreshold: 0.78,
          lowSeparationExtraToleranceCents: 20,
          lowSeparationExtraRhythmToleranceMs: 16,
          extraDurationToleranceRatio: 0.1,
          measureTrendToleranceMs: 80,
          measureInstabilityToleranceMs: 56,
          rhythmMissingConfidenceThreshold: 0.08,
          coarseRhythmReviewThresholdMs: 900,
          lowConfidenceRhythmReviewThresholdMs: 1800,
          octaveFlexMaxSteps: 4,
          coarseScoreReviewThresholdCents: 3400,
          isolatedPitchReviewThresholdCents: 3400,
          uncertainPenaltyScale: 0,
          scoreGuideGain: 0.36,
          scoreGuideBandwidthCents: 28,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-sm1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-sm2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 78 },
          { noteId: "tw-sm3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-sm4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-sm5", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-sm6", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-sm7", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 83 },
          { noteId: "tw-sm8", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 86 },
          { noteId: "tw-sm9", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 84 },
        ],
      },
      {
        sectionId: "martial-pulse",
        title: "\u519b\u9f13\u5f0f\u52a8\u673a",
        tempo: 128,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 20,
        researchWindowHints: [178, 180, 182],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 6,
          extraRhythmToleranceMs: 14,
          lowSeparationThreshold: 0.58,
          lowSeparationExtraToleranceCents: 8,
          lowSeparationExtraRhythmToleranceMs: 16,
          extraDurationToleranceRatio: 0.08,
          measureTrendToleranceMs: 84,
          measureInstabilityToleranceMs: 56,
          coarseRhythmReviewThresholdMs: 900,
          lowConfidenceRhythmReviewThresholdMs: 1800,
          octaveFlexMaxSteps: 1,
          coarseScoreReviewThresholdCents: 820,
          isolatedPitchReviewThresholdCents: 320,
          uncertainPenaltyScale: 0,
          rhythmIssuePenaltyScale: 0.55,
          measureFindingPenaltyScale: 0.45,
          scoreGuideGain: 0.34,
          scoreGuideBandwidthCents: 38,
          scoreGuideConfidenceFloor: 0.7,
        },
        notes: [
          { noteId: "tw-mp1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-mp2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-mp3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-mp4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-mp5", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 83 },
          { noteId: "tw-mp6", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-mp7", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 86 },
          { noteId: "tw-mp8", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 84 },
        ],
      },
      {
        sectionId: "accented-unison",
        title: "\u5f3a\u594f\u9f50\u594f\u53e5",
        tempo: 132,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 21,
        researchWindowHints: [190, 192, 194],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 16,
          extraRhythmToleranceMs: 12,
          lowSeparationThreshold: 0.8,
          lowSeparationExtraToleranceCents: 24,
          lowSeparationExtraRhythmToleranceMs: 16,
          extraDurationToleranceRatio: 0.1,
          measureTrendToleranceMs: 76,
          measureInstabilityToleranceMs: 52,
          rhythmMissingConfidenceThreshold: 0.08,
          coarseRhythmReviewThresholdMs: 900,
          lowConfidenceRhythmReviewThresholdMs: 1800,
          octaveFlexMaxSteps: 3,
          coarseScoreReviewThresholdCents: 2600,
          isolatedPitchReviewThresholdCents: 2600,
          uncertainPenaltyScale: 0,
          scoreGuideGain: 0.38,
          scoreGuideBandwidthCents: 30,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-au1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 86 },
          { noteId: "tw-au2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 84 },
          { noteId: "tw-au3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-au4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-au5", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-au6", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 84 },
          { noteId: "tw-au7", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-au8", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 79 },
        ],
      },
      {
        sectionId: "lyrical-return-b",
        title: "\u6292\u60c5\u56de\u5f52 B",
        tempo: 120,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 22,
        researchWindowHints: [202, 204, 206],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 8,
          lowSeparationThreshold: 0.58,
          lowSeparationExtraToleranceCents: 10,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 540,
          scoreGuideGain: 0.42,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-lb1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-lb2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-lb3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-lb4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-lb5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 84 },
          { noteId: "tw-lb6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-lb7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-lb8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 74 },
        ],
      },
      {
        sectionId: "rubato-cadenza",
        title: "rubato \u534e\u5f69\u53e5",
        tempo: 84,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 23,
        researchWindowHints: [214, 216, 218],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          extraRhythmToleranceMs: 18,
          lowSeparationThreshold: 0.7,
          lowSeparationExtraToleranceCents: 12,
          lowSeparationExtraRhythmToleranceMs: 14,
          extraDurationToleranceRatio: 0.14,
          measureTrendToleranceMs: 90,
          measureInstabilityToleranceMs: 60,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1800,
          lowConfidenceRhythmReviewThresholdMs: 2600,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 700,
          isolatedPitchReviewThresholdCents: 260,
          scoreGuideGain: 0.34,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-rb1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 64 },
          { noteId: "tw-rb2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 66 },
          { noteId: "tw-rb3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-rb4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 71 },
          { noteId: "tw-rb5", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 69 },
          { noteId: "tw-rb6", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-rb7", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-rb8", measureIndex: 2, beatStart: 0, beatDuration: 2, midiPitch: 84 },
        ],
      },
      {
        sectionId: "accelerando-banner",
        title: "\u6e10\u5feb\u51b2\u9876\u53e5",
        tempo: 140,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 24,
        researchWindowHints: [226, 228, 230],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 12,
          extraRhythmToleranceMs: 20,
          lowSeparationThreshold: 0.74,
          lowSeparationExtraToleranceCents: 16,
          lowSeparationExtraRhythmToleranceMs: 16,
          extraDurationToleranceRatio: 0.12,
          measureTrendToleranceMs: 90,
          measureInstabilityToleranceMs: 60,
          rhythmMissingConfidenceThreshold: 0.08,
          coarseRhythmReviewThresholdMs: 1200,
          lowConfidenceRhythmReviewThresholdMs: 2000,
          octaveFlexMaxSteps: 3,
          coarseScoreReviewThresholdCents: 2000,
          isolatedPitchReviewThresholdCents: 1800,
          scoreGuideGain: 0.36,
          scoreGuideBandwidthCents: 30,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-ab1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 84 },
          { noteId: "tw-ab2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 72 },
          { noteId: "tw-ab3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 86 },
          { noteId: "tw-ab4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-ab5", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 88 },
          { noteId: "tw-ab6", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-ab7", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 91 },
          { noteId: "tw-ab8", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 93 },
        ],
      },
      {
        sectionId: "drone-climb-finale",
        title: "\u6301\u7eed\u97f3\u6536\u675f\u4e0a\u884c",
        tempo: 138,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 25,
        researchWindowHints: [238, 240, 242],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 8,
          extraRhythmToleranceMs: 24,
          lowSeparationThreshold: 0.72,
          lowSeparationExtraToleranceCents: 10,
          lowSeparationExtraRhythmToleranceMs: 16,
          extraDurationToleranceRatio: 0.16,
          measureTrendToleranceMs: 84,
          measureInstabilityToleranceMs: 56,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1400,
          lowConfidenceRhythmReviewThresholdMs: 2200,
          octaveFlexMaxSteps: 1,
          coarseScoreReviewThresholdCents: 520,
          isolatedPitchReviewThresholdCents: 340,
          scoreGuideGain: 0.3,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-dc1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-dc2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-dc3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-dc4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-dc5", measureIndex: 1, beatStart: 2, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-dc6", measureIndex: 1, beatStart: 2.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-dc7", measureIndex: 1, beatStart: 3, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-dc8", measureIndex: 1, beatStart: 3.5, beatDuration: 0.5, midiPitch: 84 },
          { noteId: "tw-dc9", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 86 },
          { noteId: "tw-dc10", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 88 },
        ],
      },
      {
        sectionId: "vivace-accent-grid",
        title: "Allegro Vivace \u91cd\u97f3\u7f51\u683c",
        tempo: 160,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 26,
        researchWindowHints: [254, 256, 258],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          extraRhythmToleranceMs: 12,
          lowSeparationThreshold: 0.82,
          lowSeparationExtraToleranceCents: 10,
          lowSeparationExtraRhythmToleranceMs: 10,
          extraDurationToleranceRatio: 0.08,
          measureTrendToleranceMs: 72,
          measureInstabilityToleranceMs: 48,
          rhythmMissingConfidenceThreshold: 0.08,
          coarseRhythmReviewThresholdMs: 850,
          lowConfidenceRhythmReviewThresholdMs: 1400,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 1400,
          isolatedPitchReviewThresholdCents: 260,
          scoreGuideGain: 0.42,
          scoreGuideBandwidthCents: 30,
          scoreGuideConfidenceFloor: 0.76,
        },
        notes: [
          { noteId: "tw-vg1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 62 },
          { noteId: "tw-vg2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-vg3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 62 },
          { noteId: "tw-vg4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-vg5", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 69 },
          { noteId: "tw-vg6", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 71 },
          { noteId: "tw-vg7", measureIndex: 2, beatStart: 0, beatDuration: 0.5, midiPitch: 62 },
          { noteId: "tw-vg8", measureIndex: 2, beatStart: 0.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-vg9", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-vg10", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 76 },
        ],
      },
      {
        sectionId: "pedal-leap-sequence",
        title: "\u652f\u70b9\u8df3\u8fdb\u53e5",
        tempo: 158,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 27,
        researchWindowHints: [266, 268, 270],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 8,
          extraRhythmToleranceMs: 20,
          lowSeparationThreshold: 0.72,
          lowSeparationExtraToleranceCents: 8,
          lowSeparationExtraRhythmToleranceMs: 12,
          extraDurationToleranceRatio: 0.12,
          measureTrendToleranceMs: 78,
          measureInstabilityToleranceMs: 54,
          rhythmMissingConfidenceThreshold: 0.08,
          coarseRhythmReviewThresholdMs: 900,
          lowConfidenceRhythmReviewThresholdMs: 1800,
          octaveFlexMaxSteps: 1,
          coarseScoreReviewThresholdCents: 560,
          isolatedPitchReviewThresholdCents: 220,
          scoreGuideGain: 0.3,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-pl1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 62 },
          { noteId: "tw-pl2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-pl3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 69 },
          { noteId: "tw-pl4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 71 },
          { noteId: "tw-pl5", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-pl6", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 71 },
          { noteId: "tw-pl7", measureIndex: 2, beatStart: 0, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-pl8", measureIndex: 2, beatStart: 0.5, beatDuration: 0.5, midiPitch: 69 },
          { noteId: "tw-pl9", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-pl10", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 79 },
        ],
      },
      {
        sectionId: "tremolo-surge",
        title: "\u9884\u793a\u8fdb\u5165\u4e0e\u6ed1\u97f3\u51b2\u523a",
        tempo: 164,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 28,
        researchWindowHints: [278, 280, 282],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 12,
          extraRhythmToleranceMs: 24,
          lowSeparationThreshold: 0.72,
          lowSeparationExtraToleranceCents: 10,
          lowSeparationExtraRhythmToleranceMs: 10,
          extraDurationToleranceRatio: 0.1,
          measureTrendToleranceMs: 1200,
          measureInstabilityToleranceMs: 52,
          rhythmMissingConfidenceThreshold: 0.08,
          coarseRhythmReviewThresholdMs: 2000,
          lowConfidenceRhythmReviewThresholdMs: 3200,
          octaveFlexMaxSteps: 3,
          coarseScoreReviewThresholdCents: 760,
          isolatedPitchReviewThresholdCents: 260,
          uncertainPenaltyScale: 0.35,
          rhythmIssuePenaltyScale: 0.4,
          measureFindingPenaltyScale: 0.35,
          scoreGuideGain: 0.4,
          scoreGuideBandwidthCents: 30,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-ts1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 62 },
          { noteId: "tw-ts2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-ts3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 62 },
          { noteId: "tw-ts4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-ts5", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-ts6", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-ts7", measureIndex: 2, beatStart: 0, beatDuration: 0.5, midiPitch: 83 },
          { noteId: "tw-ts8", measureIndex: 2, beatStart: 0.5, beatDuration: 0.5, midiPitch: 86 },
          { noteId: "tw-ts9", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 88 },
          { noteId: "tw-ts10", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 91 },
        ],
      },
        {
          sectionId: "folk-dance-answer",
          title: "\u6c11\u95f4\u821e\u6b65\u5e94\u7b54",
          tempo: 150,
          meter: "4/4",
          demoAudio: "",
          sequenceIndex: 29,
          researchWindowHints: [290, 292, 294],
          calibrationProfile: {
            scoreCoarse: true,
            preferScoreBoundaries: true,
            extraPitchToleranceCents: 8,
            lowSeparationThreshold: 0.78,
            lowSeparationExtraToleranceCents: 8,
            octaveFlexMaxSteps: 1,
            coarseScoreReviewThresholdCents: 600,
            isolatedPitchReviewThresholdCents: 220,
            scoreGuideGain: 0.3,
            scoreGuideBandwidthCents: 34,
            scoreGuideConfidenceFloor: 0.72,
          },
          notes: [
            { noteId: "tw-fd1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 74 },
            { noteId: "tw-fd2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 76 },
            { noteId: "tw-fd3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-fd4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 71 },
          { noteId: "tw-fd5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 69 },
          { noteId: "tw-fd6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 71 },
          { noteId: "tw-fd7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-fd8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-fd9", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 74 },
        ],
      },
      {
        sectionId: "rustic-turn",
        title: "\u4e61\u98ce\u8f6c\u56de\u53e5",
        tempo: 148,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 30,
        researchWindowHints: [302, 304, 306],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 4,
          extraRhythmToleranceMs: 24,
          lowSeparationThreshold: 0.62,
          lowSeparationExtraToleranceCents: 6,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.14,
          measureTrendToleranceMs: 1200,
          measureInstabilityToleranceMs: 64,
          coarseRhythmReviewThresholdMs: 1800,
          lowConfidenceRhythmReviewThresholdMs: 2800,
          octaveFlexMaxSteps: 1,
          coarseScoreReviewThresholdCents: 540,
          uncertainPenaltyScale: 0.35,
          rhythmIssuePenaltyScale: 0.45,
          measureFindingPenaltyScale: 0.4,
          scoreGuideGain: 0.28,
          scoreGuideBandwidthCents: 40,
          scoreGuideConfidenceFloor: 0.68,
        },
        notes: [
          { noteId: "tw-rt1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 69 },
          { noteId: "tw-rt2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 71 },
          { noteId: "tw-rt3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 72 },
          { noteId: "tw-rt4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-rt5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-rt6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-rt7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-rt8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-rt9", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 71 },
        ],
      },
      {
        sectionId: "development-launch",
        title: "\u53d1\u5c55\u90e8\u52a8\u673a",
        tempo: 152,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 31,
        researchWindowHints: [314, 316, 318],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          extraRhythmToleranceMs: 22,
          lowSeparationThreshold: 0.72,
          lowSeparationExtraToleranceCents: 14,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.14,
          measureTrendToleranceMs: 90,
          measureInstabilityToleranceMs: 60,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1200,
          lowConfidenceRhythmReviewThresholdMs: 2600,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 1800,
          isolatedPitchReviewThresholdCents: 1600,
          scoreGuideGain: 0.34,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-dl1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 66 },
          { noteId: "tw-dl2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 67 },
          { noteId: "tw-dl3", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 69 },
          { noteId: "tw-dl4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-dl5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 71 },
          { noteId: "tw-dl6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-dl7", measureIndex: 2, beatStart: 1, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-dl8", measureIndex: 2, beatStart: 1.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-dl9", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-dl10", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 76 },
        ],
      },
      {
        sectionId: "ostinato-dialogue",
        title: "\u6301\u7eed\u97f3\u5bf9\u8bdd",
        tempo: 154,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 32,
        researchWindowHints: [326, 328, 330],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 12,
          extraRhythmToleranceMs: 12,
          lowSeparationThreshold: 0.74,
          lowSeparationExtraToleranceCents: 16,
          lowSeparationExtraRhythmToleranceMs: 16,
          extraDurationToleranceRatio: 0.08,
          measureTrendToleranceMs: 70,
          measureInstabilityToleranceMs: 52,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 900,
          lowConfidenceRhythmReviewThresholdMs: 1800,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 680,
          isolatedPitchReviewThresholdCents: 260,
          uncertainPenaltyScale: 0.0,
          rhythmIssuePenaltyScale: 0.5,
          measureFindingPenaltyScale: 0.4,
          scoreGuideGain: 0.34,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.7,
        },
        notes: [
          { noteId: "tw-od1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-od2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-od3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-od4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 71 },
          { noteId: "tw-od5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 69 },
          { noteId: "tw-od6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 67 },
          { noteId: "tw-od7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 71 },
          { noteId: "tw-od8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-od9", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 79 },
        ],
      },
      {
        sectionId: "bright-recap-fanfare",
        title: "\u660e\u4eae\u518d\u73b0\u53f7\u89d2",
        tempo: 156,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 33,
        researchWindowHints: [338, 340, 342],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 8,
          extraRhythmToleranceMs: 18,
          lowSeparationThreshold: 0.68,
          lowSeparationExtraToleranceCents: 10,
          lowSeparationExtraRhythmToleranceMs: 12,
          extraDurationToleranceRatio: 0.1,
          measureTrendToleranceMs: 72,
          measureInstabilityToleranceMs: 52,
          rhythmMissingConfidenceThreshold: 0.08,
          coarseRhythmReviewThresholdMs: 900,
          lowConfidenceRhythmReviewThresholdMs: 1600,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 600,
          isolatedPitchReviewThresholdCents: 220,
          scoreGuideGain: 0.32,
          scoreGuideBandwidthCents: 32,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-bf1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 69 },
          { noteId: "tw-bf2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 71 },
          { noteId: "tw-bf3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-bf4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 78 },
          { noteId: "tw-bf5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-bf6", measureIndex: 2, beatStart: 0, beatDuration: 0.5, midiPitch: 83 },
          { noteId: "tw-bf7", measureIndex: 2, beatStart: 0.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-bf8", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-bf9", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-bf10", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 74 },
        ],
      },
      {
        sectionId: "crest-ostinato-rise",
        title: "\u9ad8\u70b9\u6301\u7eed\u4e0a\u626c",
        tempo: 158,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 34,
        researchWindowHints: [350, 352, 354],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          extraRhythmToleranceMs: 16,
          lowSeparationThreshold: 0.66,
          lowSeparationExtraToleranceCents: 10,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.1,
          measureTrendToleranceMs: 86,
          measureInstabilityToleranceMs: 58,
          coarseRhythmReviewThresholdMs: 1200,
          lowConfidenceRhythmReviewThresholdMs: 2200,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 560,
          isolatedPitchReviewThresholdCents: 320,
          uncertainPenaltyScale: 0,
          rhythmIssuePenaltyScale: 0.55,
          measureFindingPenaltyScale: 0.45,
          scoreGuideGain: 0.36,
          scoreGuideBandwidthCents: 30,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-cor1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-cor2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-cor3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-cor4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 84 },
          { noteId: "tw-cor5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 86 },
          { noteId: "tw-cor6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 88 },
          { noteId: "tw-cor7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 86 },
          { noteId: "tw-cor8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 84 },
          { noteId: "tw-cor9", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 81 },
        ],
      },
        {
          sectionId: "descending-beacon",
          title: "\u4e0b\u884c\u4fe1\u53f7\u94fe",
          tempo: 154,
          meter: "4/4",
          demoAudio: "",
          sequenceIndex: 35,
          researchWindowHints: [362, 364, 366],
          calibrationProfile: {
            scoreCoarse: true,
            preferScoreBoundaries: true,
            extraPitchToleranceCents: 10,
            extraRhythmToleranceMs: 16,
            lowSeparationExtraRhythmToleranceMs: 10,
            extraDurationToleranceRatio: 0.1,
            measureTrendToleranceMs: 70,
            measureInstabilityToleranceMs: 48,
            rhythmMissingConfidenceThreshold: 0.08,
            coarseRhythmReviewThresholdMs: 800,
            lowConfidenceRhythmReviewThresholdMs: 1600,
            lowSeparationThreshold: 0.72,
            lowSeparationExtraToleranceCents: 10,
            octaveFlexMaxSteps: 2,
            coarseScoreReviewThresholdCents: 620,
            isolatedPitchReviewThresholdCents: 220,
            scoreGuideGain: 0.34,
            scoreGuideBandwidthCents: 30,
            scoreGuideConfidenceFloor: 0.74,
          },
          notes: [
            { noteId: "tw-db1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 88 },
            { noteId: "tw-db2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 86 },
            { noteId: "tw-db3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 84 },
          { noteId: "tw-db4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-db5", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-db6", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-db7", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-db8", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 72 },
          { noteId: "tw-db9", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 69 },
        ],
      },
        {
          sectionId: "pedal-tension-loop",
          title: "\u8e0f\u97f3\u7d27\u5f20\u5faa\u73af",
          tempo: 150,
          meter: "4/4",
          demoAudio: "",
          sequenceIndex: 36,
          researchWindowHints: [374, 376, 378],
          calibrationProfile: {
            scoreCoarse: true,
            preferScoreBoundaries: true,
            extraPitchToleranceCents: 10,
            extraRhythmToleranceMs: 22,
            lowSeparationExtraRhythmToleranceMs: 18,
            extraDurationToleranceRatio: 0.12,
            measureTrendToleranceMs: 80,
            measureInstabilityToleranceMs: 56,
            rhythmMissingConfidenceThreshold: 0.06,
            coarseRhythmReviewThresholdMs: 900,
            lowConfidenceRhythmReviewThresholdMs: 2400,
            lowSeparationThreshold: 0.64,
            lowSeparationExtraToleranceCents: 12,
            octaveFlexMaxSteps: 2,
            coarseScoreReviewThresholdCents: 640,
            isolatedPitchReviewThresholdCents: 240,
            scoreGuideGain: 0.38,
            scoreGuideBandwidthCents: 32,
            scoreGuideConfidenceFloor: 0.74,
          },
          notes: [
            { noteId: "tw-pt1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 76 },
            { noteId: "tw-pt2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 74 },
            { noteId: "tw-pt3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-pt4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-pt5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-pt6", measureIndex: 2, beatStart: 0, beatDuration: 0.5, midiPitch: 83 },
          { noteId: "tw-pt7", measureIndex: 2, beatStart: 0.5, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-pt8", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-pt9", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-pt10", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 74 },
        ],
      },
      {
        sectionId: "open-string-sprint",
        title: "\u7a7a\u5f26\u51b2\u523a\u53e5",
        tempo: 164,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 37,
        researchWindowHints: [386, 388, 390],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 8,
          lowSeparationThreshold: 0.68,
          lowSeparationExtraToleranceCents: 10,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 520,
          isolatedPitchReviewThresholdCents: 220,
          scoreGuideGain: 0.3,
          scoreGuideBandwidthCents: 30,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-os1", measureIndex: 1, beatStart: 0, beatDuration: 0.5, midiPitch: 69 },
          { noteId: "tw-os2", measureIndex: 1, beatStart: 0.5, beatDuration: 0.5, midiPitch: 71 },
          { noteId: "tw-os3", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 74 },
          { noteId: "tw-os4", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-os5", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-os6", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-os7", measureIndex: 2, beatStart: 0, beatDuration: 0.5, midiPitch: 84 },
          { noteId: "tw-os8", measureIndex: 2, beatStart: 0.5, beatDuration: 0.5, midiPitch: 86 },
          { noteId: "tw-os9", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 88 },
          { noteId: "tw-os10", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 91 },
        ],
      },
      {
        sectionId: "stacked-fanfare-hits",
        title: "\u53e0\u7f6e\u53f7\u89d2\u51fb\u70b9",
        tempo: 152,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 38,
        researchWindowHints: [398, 400, 402],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          lowSeparationThreshold: 0.6,
          lowSeparationExtraToleranceCents: 12,
          octaveFlexMaxSteps: 3,
          coarseScoreReviewThresholdCents: 700,
          scoreGuideGain: 0.52,
          scoreGuideBandwidthCents: 32,
          scoreGuideConfidenceFloor: 0.74,
        },
        notes: [
          { noteId: "tw-sf1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 91 },
          { noteId: "tw-sf2", measureIndex: 1, beatStart: 1, beatDuration: 1, midiPitch: 88 },
          { noteId: "tw-sf3", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 86 },
          { noteId: "tw-sf4", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 84 },
          { noteId: "tw-sf5", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-sf6", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-sf7", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-sf8", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 74 },
        ],
      },
      {
        sectionId: "rubato-breakturn",
        title: "rubato \u65ad\u5f00\u8f6c\u56de",
        tempo: 132,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 39,
        researchWindowHints: [410, 412, 414],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 10,
          extraRhythmToleranceMs: 18,
          lowSeparationThreshold: 0.65,
          lowSeparationExtraToleranceCents: 14,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.16,
          measureTrendToleranceMs: 96,
          measureInstabilityToleranceMs: 64,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1200,
          lowConfidenceRhythmReviewThresholdMs: 2400,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 760,
          isolatedPitchReviewThresholdCents: 280,
          uncertainPenaltyScale: 0,
          scoreGuideGain: 0.28,
          scoreGuideBandwidthCents: 36,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-rbt1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-rbt2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 81 },
          { noteId: "tw-rbt3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 83 },
          { noteId: "tw-rbt4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 86 },
          { noteId: "tw-rbt5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 88 },
          { noteId: "tw-rbt6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 84 },
          { noteId: "tw-rbt7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-rbt8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 79 },
        ],
      },
      {
        sectionId: "final-ostinato-rally",
        title: "\u7ec8\u6bb5\u56fa\u5b9a\u97f3\u63a8\u8fdb",
        tempo: 150,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 40,
        researchWindowHints: [422, 424, 426],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 16,
          extraRhythmToleranceMs: 14,
          lowSeparationThreshold: 0.9,
          lowSeparationExtraToleranceCents: 28,
          lowSeparationExtraRhythmToleranceMs: 18,
          extraDurationToleranceRatio: 0.12,
          measureTrendToleranceMs: 82,
          measureInstabilityToleranceMs: 56,
          rhythmMissingConfidenceThreshold: 0.06,
          coarseRhythmReviewThresholdMs: 1000,
          lowConfidenceRhythmReviewThresholdMs: 2200,
          octaveFlexMaxSteps: 4,
          coarseScoreReviewThresholdCents: 3600,
          isolatedPitchReviewThresholdCents: 3600,
          uncertainPenaltyScale: 0.0,
          rhythmIssuePenaltyScale: 0.55,
          measureFindingPenaltyScale: 0.45,
          scoreGuideGain: 0.44,
          scoreGuideBandwidthCents: 30,
          scoreGuideConfidenceFloor: 0.78,
        },
        notes: [
          { noteId: "tw-for1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-for2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 76 },
          { noteId: "tw-for3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 79 },
          { noteId: "tw-for4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-for5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 84 },
          { noteId: "tw-for6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 86 },
          { noteId: "tw-for7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 88 },
          { noteId: "tw-for8", measureIndex: 2, beatStart: 2, beatDuration: 1, midiPitch: 91 },
          { noteId: "tw-for9", measureIndex: 2, beatStart: 3, beatDuration: 1, midiPitch: 88 },
        ],
      },
      {
        sectionId: "coda-release",
        title: "\u5c3e\u58f0\u653e\u5f00\u53e5",
        tempo: 126,
        meter: "4/4",
        demoAudio: "",
        sequenceIndex: 41,
        researchWindowHints: [434, 436, 438],
        calibrationProfile: {
          scoreCoarse: true,
          preferScoreBoundaries: true,
          extraPitchToleranceCents: 8,
          lowSeparationThreshold: 0.6,
          lowSeparationExtraToleranceCents: 10,
          octaveFlexMaxSteps: 2,
          coarseScoreReviewThresholdCents: 520,
          scoreGuideGain: 0.4,
          scoreGuideBandwidthCents: 34,
          scoreGuideConfidenceFloor: 0.72,
        },
        notes: [
          { noteId: "tw-cr1", measureIndex: 1, beatStart: 0, beatDuration: 1, midiPitch: 88 },
          { noteId: "tw-cr2", measureIndex: 1, beatStart: 1, beatDuration: 0.5, midiPitch: 86 },
          { noteId: "tw-cr3", measureIndex: 1, beatStart: 1.5, beatDuration: 0.5, midiPitch: 84 },
          { noteId: "tw-cr4", measureIndex: 1, beatStart: 2, beatDuration: 1, midiPitch: 81 },
          { noteId: "tw-cr5", measureIndex: 1, beatStart: 3, beatDuration: 1, midiPitch: 79 },
          { noteId: "tw-cr6", measureIndex: 2, beatStart: 0, beatDuration: 1, midiPitch: 76 },
          { noteId: "tw-cr7", measureIndex: 2, beatStart: 1, beatDuration: 1, midiPitch: 74 },
          { noteId: "tw-cr8", measureIndex: 2, beatStart: 2, beatDuration: 2, midiPitch: 71 },
        ],
      },
    ],
  },
];

function summarizeSection(section) {
  const totalBeats = section.notes.reduce((sum, note) => sum + Number(note.beatDuration || 0), 0);
  return {
    sectionId: section.sectionId,
    title: section.title,
    tempo: section.tempo,
    meter: section.meter,
    demoAudio: section.demoAudio,
    sequenceIndex: section.sequenceIndex,
    researchWindowHints: section.researchWindowHints || [],
    noteCount: section.notes.length,
    measureCount: Math.max(...section.notes.map((note) => Number(note.measureIndex || 1))),
    totalBeats,
  };
}

export function getErhuPieceSummaries() {
  return ERHU_STUDY_PIECES.map((piece) => ({
    pieceId: piece.pieceId,
    title: piece.title,
    composer: piece.composer,
    targetSkills: piece.targetSkills,
    difficulty: piece.difficulty,
    coverageMode: piece.coverageMode || "fragment",
    sourceAudio: piece.sourceAudio || "",
    sourceScore: piece.sourceScore || "",
    wholePieceExportReady: Boolean(piece.wholePieceExportReady),
    sections: piece.sections.map((section) => summarizeSection(section)),
  }));
}

export function getErhuPiece(pieceId) {
  return ERHU_STUDY_PIECES.find((piece) => piece.pieceId === pieceId) || null;
}

export function getErhuSection(pieceId, sectionId) {
  const piece = getErhuPiece(pieceId);
  if (!piece) return null;
  const section = piece.sections.find((item) => item.sectionId === sectionId) || null;
  if (!section) return null;
  return {
    pieceId: piece.pieceId,
    title: piece.title,
    composer: piece.composer,
    targetSkills: piece.targetSkills,
    difficulty: piece.difficulty,
    ...section,
  };
}
